- content/en/docs-style-guide.md
Just adding this sample so it's clear how to do alerts.
`{{%/* alert title="Note" %}} 
This is a sample note.
{{% /alert */%}}`
> Added code sample for Alerts

- layouts/partials/related.html
> Link to anchors via RelatedContent

- config.toml
- content/en/search.md
- layouts/_default/search.html
- static/robots.txt
Search engine crawling is improved with this PR, as is internal search on the site as it now uses Google search. 
For #138
> Improve Searchability

- content/en/apps/reference/api.md
- layouts/shortcodes/toc.html
> Import API

- content/en/apps/reference/app-settings/dhis2.md
> Changes dhis2 setting name to use snake_case

- content/en/core/process/workflow.md
initial draft for review/discussion. Once we have an agreed upon draft to publish, we may want to move this section to a separate page within the doc site hierarchy. 
Also includes a couple of formatting improvements to the Development Workflow (noticed as I was reviewing).
> Documentation workflow

- content/en/apps/reference/api.md
> Adds documentation about `contacts_by_phone` api

- content/en/apps/reference/app-settings/header_tabs.md
> Adds app_settings.header_tabs

- content/en/apps/guides/database/_index.md
- content/en/core/overview/architecture.md
> Add documentation about dbs

- content/en/apps/reference/app-settings/outbound.md
> Added documentation for send semantics

- assets/scss/_variables_project.scss
For https://github.com/medic/cht-docs/issues/183
@MaxDiz this could replace https://github.com/medic/cht-docs/pull/192. Please test to see if this work as needed.
> Prevents alert showing over image

- content/en/contribute/docs/style-guide.md
> fix images code sample on style guide

- content/en/apps/reference/_index.md
- layouts/partials/navbar.html
Adds Reference to top nav bar, as per #217
> 217 refererence in nav

- content/en/contribute/docs/style-guide.md
missed feedback in PR#203  for issue#178
> fix sentance with orphaned "this" per feedback

- content/en/apps/guides/performance/replication.md
- content/en/apps/reference/app-settings/replication_depth.md
> Adds documentation about replication depth

- content/en/apps/reference/app-settings/reminders.md
> Add reminders documentation

- content/en/apps/tutorials/application-settings.md
New tutorial on application settings
> Add application settings tutorial

- content/en/apps/tutorials/sms-forms.md
> Add sms forms tutorial

- content/en/apps/reference/api.md
Updated docs to show the one we do look at.
> Property referenced in doc does not exist

- content/en/apps/reference/api.md
- content/en/apps/reference/app-settings/_index.md
- content/en/apps/reference/app-settings/token_login.md
> Adds documentation about enabling login in via token link. 

- content/en/apps/guides/performance/replication.md
> Adds info about `fields.private`

- content/en/apps/examples/anc.md
fix link and minor text update based on @isaacholeman feedback
> maternal and newborn minor updates

- .github/CODEOWNERS
Codeowners assigned to help with the PR process. The assignments were discussed with @MaxDiz and @michaelkohn.
> Initial commit of codeowners files

- content/en/contribute/code/workflow.md
Documenting some changes we as QAs have agreed to.
> QA Process changes

- content/en/apps/tutorials/local-setup.md
add test data install instructions at the request of @isaacholeman
> update local enviro setup tutorial with test data install

- content/en/apps/tutorials/application-settings.md
- content/en/apps/tutorials/sms-forms.md
Order app building tutorials logically.
> Update weights to order tutorials correctly

- content/en/apps/tutorials/sms-schedules.md
Add new SMS schedules tutorial as follow up to SMS forms tutorial.
Closes #272
> Add sms schedules tutorial

- content/en/apps/guides/performance/replication.md
> fix bad see also link

- content/en/apps/concepts/users.md
- content/en/apps/features/contacts/_index.md
- content/en/apps/features/reports/_index.md
updates to Reports, Contacts, and Users pages to coincide with replication depth improvement made in v3.10 - https://github.com/medic/cht-docs/pull/58
closes: https://github.com/medic/cht-docs/issues/226
> repliaction depth user education improvements v3.10

- content/en/apps/concepts/workflows.md
> remove link in related

- content/en/apps/tutorials/app-forms.md
A new tutorial that shows how to develop CHT application forms
Issue #276
> Add a new app forms tutorial

- content/en/core/overview/supported-software.md
> Updated supported versions for 3.10.0 release

- content/en/apps/reference/api.md
This PR will add documentation for the new endpoint that returns information about users who replicate document.
Also updates the monitor endpoint documentation to include a new property about the number of users that exceeded replication limit.
medic/cht-core#6251
> #6251 Replication limit

- content/en/apps/tutorials/form-properties.md
Closes https://github.com/medic/cht-docs/issues/276
> CHT form properties tutorial

- content/en/apps/reference/forms/app.md
I think this probably could be better but is very bare minimum. I couldn't think of better words this morning to describe what the functions do.  A more in depth ticket about using functions, operators, and maybe a guide on using calculations might be a future ticket.
> add reference to xpath functions

- content/en/apps/reference/forms/app.md
Taken from https://github.com/medic/medic-docs/blob/91badc2a347f86fd2b42b1c9ab9527b5982ee9c0/configuration/forms.md#supported-xlsform-meta-fields
> Adds XLSForm meta fields

- content/en/apps/guides/performance/telemetry.md
Adds a sample of telemetry doc.
Resolves #202
> Add telemetry sample payload.

- content/en/design/personas/chw-janet.md
Fix on [the persona page](https://docs.communityhealthtoolkit.org/design/personas/chw-janet/):
> She visits 10 and 15 homes daily where mny of
to 
> She visits 10 and 15 homes daily where many of
> Person page fix: 'mny' -> 'many'

- content/en/apps/tutorials/form-properties.md
Updated the` Purpose of Tutorial` section to match other docs content.
> update purpose of tutorial and fix typo

- content/en/apps/concepts/access.md
"Remote login" is misleading, as it sounds like you are logging into a person's device remotely.
> Use Magic Link as section header

- content/en/apps/tutorials/local-setup.md
- content/en/core/guides/docker-setup.md
> remove hard coded yml file, update steps, add links 

- content/en/apps/tutorials/local-setup.md
> flesh out medic-conf install steps 

- .github/workflows/ci.yml
per #367.  We'll add it back in on #366
> remove per PR link checking 

- content/en/apps/reference/forms/app.md
For https://github.com/medic/cht-docs/issues/378, with content adapted from https://github.com/medic/medic-docs/blob/91badc2a347f86fd2b42b1c9ab9527b5982ee9c0/configuration/forms.md
> Adds z-score instructions

- content/en/apps/tutorials/tasks.md
> CHT tasks tutorial

- content/en/apps/tutorials/tasks.md
in [this PR](https://github.com/medic/cht-docs/pull/322), some how a broken link got merged to master. This PR fixes that.
> Fix link to Anatomy of a Task

- content/en/design/best-practices/_index.md
like the title says! extra "Visit Information" listed in header icoons
> Remove duplicate Visit Information icon

- content/en/design/best-practices/_index.md
> fix spealling of helath -> health

- README.md
- content/en/apps/guides/forms/wealth-quintiles.md
- content/en/apps/reference/forms/app.md
Added how to configure the quintiles recording to the people profile.
> Quintiles config

- content/en/apps/concepts/_index.md
I wasn't sure exactly how to read this paragraph, so hopefully my PR doesn't change the intended meaning of anything!
Where "antenatal" was used, I preceded it with an "an". Perhaps I'm mistaken, as I'm not a CHW and not familiar with many of the terms I've been reading lately.
> makes a bullet list for form capabilities 

- content/en/contribute/docs/style-guide.md
> sets a guideline for using 'right-hand' or 'left-hand'

- content/en/apps/features/tasks/_index.md
- content/en/apps/tutorials/contact-and-users-1.md
- content/en/design/best-practices/_index.md
- content/en/design/components/_index.md
> hyphenates left- and right-hand

- content/en/apps/tutorials/tasks.md
fixing to typos: Remove extra single quote `'`, convert tick `‘` to quote `'`
> Tasks: Fix quote & ticks, fix variable names 

- content/en/apps/guides/forms/contact-forms.md
I was triggered by the incorrect use of "it's" then got carried away.
> Grammatical fixes and improvements

- content/en/apps/features/integrations/openmrs.md
I'd like to write a post on the forum announcing some new documentation available re: integrations (generic / oppia) and rather than delete OpenMRS section until there is content,I decided to create a simple blurb that links to the generic integrations stuff.
> OpenMRS integrations documentation,  very simple update as something is better than nothing

- README.md
- troubleshooting.md
> Update readme to address macos error 

- content/en/apps/reference/tasks.md
> Fixes required fields and examples

- content/en/apps/reference/nools-extras.md
> Updates Utils description and link

- content/en/apps/reference/targets.md
Minor update to remove some task references in the schema.
> Remove task references from targets schema

- content/en/apps/reference/app-settings/_index.md
- content/en/apps/reference/app-settings/forms.md
- content/en/apps/reference/app-settings/schedules.md
- content/en/apps/tutorials/sms-forms.md
- content/en/apps/tutorials/sms-schedules.md
Make it clear that the app_settings.json is now more of a generated file and shouldn't be edited.
> app_settings should no longer be directly edited

- content/en/apps/reference/forms/app.md
> Document the hidden_fields property 

- content/en/core/overview/architecture.md
This PR:
- Updates and add more information about the cht-core web applications.
**Ticket**: https://github.com/medic/angular10-migration/issues/120#issuecomment-778000405
> Updating and adding more information about the cht-core web applications

- content/en/apps/reference/app-settings/outbound.md
Per @isaacholeman's [request in slack](https://medic.slack.com/archives/CUXB9SVT5/p1614743413001400).
> change Medic 3.5 to cht-core 3.5

- content/en/core/overview/translations.md
> Updates branding

- content/en/apps/reference/app-settings/forms.md
https://github.com/medic/cht-docs/issues/450
> changed the reference that the link is potining to.

- content/en/apps/guides/data/hydration.md
- content/en/apps/guides/data/invalid-reports.md
- content/en/apps/guides/messaging/shortcodes.md
- content/en/apps/guides/performance/purging.md
- content/en/apps/reference/app-settings/_index.md
- content/en/apps/reference/app-settings/patient_reports.md
- content/en/apps/reference/app-settings/registrations.md
- content/en/apps/reference/app-settings/transitions.md
- content/en/core/overview/db-schema.md
> Updates documentation about supporting places as subjects in SMS

- content/en/apps/reference/api.md
Add documentation for the new endpoint added in this PR: https://github.com/medic/cht-core/pull/6947
Ticket: https://github.com/medic/medic-conf/issues/331
> Add '/api/v1/forms/validate' endpoint documentation

- content/en/contribute/code/workflow.md
Providing clarification and rationale for additional information to be added on GitHub issues when the issue is resolved.
> Add guidance for additional issue resolution details

- content/en/contribute/code/workflow.md
Some additional guidance has been added along with the rationale so everyone can understand the importance.
> Add clarity on e2e testing expectations.

- content/en/apps/features/integrations/dhis2.md
HRIO doesn't seem known enough to be a header. Changed CHW for consistency.
No issue, sorry.
> Updates headers

- content/en/apps/reference/tasks.md
Adds additional parameter to tasks actions `modifyContent`. 
medic/medic-conf#398
> Updates `modifyContent` to add event param 

- content/en/apps/reference/contact-page.md
This PR will:
- Add UHC Stats feature documentation in contact summary page.
Ticket: 
- https://github.com/medic/cht-core/issues/6919
Merge after these PRs:
- PR @ cht-core: https://github.com/medic/cht-core/pull/7053 
- PR @ medic-conf: https://github.com/medic/medic-conf/pull/394 
> Add UHC Stats documentation in contact summary page.

- content/en/apps/guides/hosting/ec2-setup-guide.md
- content/en/apps/guides/hosting/self-hosting.md
Also while in there I simplified the EBS upgrade steps for clarity and consistency. 
per medic/cht-core/issues/7086
> Add backup info for medic-os generally and links to CouchDB specifically

- content/en/apps/guides/performance/telemetry.md
> Adds documentation about telemetry for replication.

- content/en/apps/reference/api.md
> Adds documentation about monitoring v2

- content/en/apps/guides/performance/telemetry.md
This PR reflects the changes from https://github.com/medic/cht-core/pull/7095 , where the telemetry frequency is increased from monthly to daily in the upcoming release of the CHT.
> Telemetry with daily frequency changes

- content/en/apps/reference/app-settings/forms.md
> change to object and added note about capitalization

- content/en/core/overview/technical-roadmap.md
> Add iframe to embed technical roadmap

- content/en/apps/reference/contact-page.md
Update documentation to better describe the default behavior introduced in this [PR](https://github.com/medic/medic-conf/pull/361)
> update default behavior of appliesToType

- content/en/apps/tutorials/condition-cards.md
- content/en/apps/tutorials/contact-summary.md
https://github.com/medic/cht-docs/issues/343
> Add contact summary tutorial

- content/en/apps/reference/app-settings/transitions.md
> Adds documentation about client-side muting.

- content/en/apps/reference/_partial_cht_api.md
- content/en/apps/reference/contact-page.md
- content/en/apps/reference/targets.md
- content/en/apps/reference/tasks.md
This PR:
- Adds documentation for the CHT Script API
Ticket: https://github.com/medic/cht-core/issues/6914
CHT-Conf: https://github.com/medic/medic-conf/pull/409
CHT-Core: https://github.com/medic/cht-core/pull/7126
> 6914 Documentation for CHT Script API

- content/en/core/guides/update-dependencies.md
**Description**
There are new libraries that we can't update, this PR updates the documentation.
Ticket: https://github.com/medic/cht-core/issues/6969
> Update for the "update dependencies" page

- .github/workflows/ci.yml
> Allow CI runs for external contributions

- content/en/core/overview/supported-software.md
Updating Support page because of 3.12 release
https://github.com/medic/cht-core/issues/6943
> Updating Support page because of 3.12 release

- content/en/apps/guides/forms/multimedia.md
- content/en/apps/reference/forms/app.md
> Add link for more detail on including media

- content/en/apps/tutorials/android-wrapper.md
References [app-services-team#178](https://github.com/medic/app-services-team/issues/178)
See accompanying [facilitator's guide](https://docs.google.com/document/d/1xLiBAnUTB4yDvMEY2R-x7fOTyosY9dOu1AEhqzLx4ds/edit) and updated [training deck](https://docs.google.com/presentation/d/1ek6lzpGDCmoUWzg3E9-uOJjbwby1-_uSLSS2P_IOBkA/edit).
> Android wrapper tutorial update

- content/en/apps/guides/performance/telemetry.md
All added entries are related to the new task group landing page. 
medic/cht-core#5886
> Adds new telemetry entries documentation.

- content/en/apps/reference/api.md
> Updates documentation for users-info endpoint.

- content/en/apps/reference/app-settings/_index.md
> Adds documentation about `task_days_overdue`

- content/en/apps/examples/covid-rdt-reference-app.md
> fix video URLs 

- content/en/apps/guides/integrations/best-practices/_index.md
- content/en/apps/guides/integrations/best-practices/rapidpro.md
- content/en/apps/guides/integrations/rapidpro.md
References [app-services-team#183](https://github.com/medic/app-services-team/issues/183)
> Adds RapidPro best practices

- content/en/core/guides/android/_index.md
> Fix a typo in `guides/android/_index.md`

- content/en/apps/guides/performance/purging.md
> Updates purging documentation.

- content/en/core/guides/android/publishing.md
- content/en/core/guides/android/releasing.md
Just adding a bit more details to compliment the new issue templates being added in https://github.com/medic/cht-android/pull/235.
> Update Android releasing/publishing doc with detailed steps

- layouts/partials/sidebar-tree.html
Fixes #603
The fix looks good in all the widths I tested, and doesn't have any known negative consequences. @mrjones-plip as part of your review can you please confirm that it looks good for you as well?
> 603 Remove unnecessary right padding

- content/en/core/overview/transitions.md
> 602 Fix transition page

- .github/workflows/ci.yml
per [thread on slack](https://medic.slack.com/archives/C024KTGRW/p1643350473551689)
> Specify branch in checkout in ci, match if syntax

- content/en/apps/features/integrations/openmrs.md
The guide for OpenMRS integration is the most related content page but was missing.
> Add link to related OpenMRS guide

- content/en/core/releases/_index.md
https://github.com/medic/cht-core/issues/7348
> 7348 - EOL dates

- content/en/core/releases/3.14.0.md
per [slack thread](https://medic.slack.com/archives/C0813CQRX/p1644593917919739?thread_ts=1644536451.786769&cid=C0813CQRX):
> This appears in the release notes under "bug fixes" - but be aware that 3.14 contains the fix for [7343](https://github.com/medic/cht-core/issues/7343) which is the "mysterious logout bug" which seems quite impactful across projects
> 
> I might suggest we highlight that one in the release notes. Together with [6338](https://github.com/medic/cht-core/issues/6338) and [7187](https://github.com/medic/cht-core/issues/7187) there appears to be a theme in the release around "improved login experience"
> Update 3.14.0 release notes to highlight login improvements

- content/en/apps/_index.md
- content/en/apps/guides/database/_index.md
- content/en/apps/guides/hosting/offline.md
- content/en/apps/tutorials/local-setup.md
- content/en/core/_index.md
- content/en/core/overview/architecture.md
- content/en/core/overview/data-flows-for-analytics.md
- content/en/core/overview/offline-first.md
- content/en/why-the-cht.md
- Find and replace all copy mentioning offline-first with links.
- Also noticed a couple of branding mistakes while I was in there...
> Document offline first

- content/en/core/releases/_index.md
@abbyad Change as discussed in the meeting today.
> Document regular upgrade advice

- content/en/apps/tutorials/application-graphics.md
> Document PWA branding requirements

- content/en/core/guides/android/branding.md
- content/en/core/guides/android/releasing.md
This PR adds information about the branch and release process for new cht-android flavors.
> Adding branching details for new flavors

- content/en/glossary.md
Review please @smbuthia - glossary page as discussed. Mostly just copied and pasted off Notion. There's plenty more to add but I'm hoping everyone helps out to contribute now there's a place for this content to exist.
@mrjones-plip I tagged you because I'm not 100% happy with how this functions. Because some glossary items have a paragraph explaining them and some don't it's ended up hard to scan over. Any ideas from a Hugo expert would be appreciated!
> Add glossary page

- content/en/apps/tutorials/tasks-1.md
For https://github.com/medic/cht-docs/issues/666
@mrjones-plip should we add checks for `{{ <` as part of the build?
> Fixes link

- content/en/apps/guides/integrations/best-practices/rapidpro.md
- content/en/apps/guides/integrations/rapidpro.md
> fixes broken Rapidpro links

- content/en/apps/guides/performance/purging.md
> Update purging documentation for offline first

- content/en/design/guides/designing-interviews.md
As we develop a supervisor reference app, we are using the resources and tools in that process to update and flesh out our design documentation. This interview guide example is a simplified version of the one that was used to design the supervisor reference app and will be linked as a resource in the reference app documentation.
> Add interview guide example

- content/en/apps/reference/app-settings/user-permissions.md
Per #medic/cht-core/issues/7139
> update documentation to add new can_upgrade permission

- content/en/core/releases/3.15.0.md
- content/en/core/releases/_index.md
> Document the cht-core 3.15.0 release

- content/en/core/guides/android/publishing.md
> fix 404 page so it redirects 

- content/en/apps/guides/debugging/replicating-production-data-locally.md
- content/en/apps/guides/debugging/secure-sharing-of-developer-instance.md
- content/en/apps/guides/hosting/app-developer.md
- content/en/apps/guides/hosting/core-developer.md
- content/en/core/guides/android/development-setup.md
- content/en/core/guides/using-windows.md
per #700, add a new doc that simplifies [the current developer](https://github.com/medic/cht-core/blob/575bc95a8ccf82b211a13fec9d3228f71169405f/DEVELOPMENT.md) hosting doc to easy, copy and paste-able steps.
> Redo developer install steps for happy path 

- content/en/apps/features/supervision/_index.md
- content/en/apps/features/targets/_index.md
> updates targets notes

- content/en/apps/guides/security/securing-android.md
> Updates to MDM section

- content/en/apps/guides/security/securing-android.md
- content/en/core/guides/android/publishing.md
For #716, in response to https://github.com/medic/cht-docs/pull/717#discussion_r906870287
> 716 consolidation of MDM changes

- content/en/apps/reference/app-settings/user-permissions.md
> Clarify use of can_edit

- content/en/apps/tutorials/couch2pg-setup.md
> adds couch2pg tutorial

- content/en/apps/reference/forms/app.md
> Correct the link for #676

- content/en/apps/guides/database/_index.md
- content/en/apps/guides/messaging/gateways/africas-talking.md
- content/en/apps/guides/messaging/gateways/rapidpro.md
- content/en/apps/reference/api.md
- content/en/apps/reference/app-settings/outbound.md
> Add documentation for credentials API

- content/en/apps/reference/forms/contact.md
> Correct contact create form permissions

- content/en/apps/reference/tasks.md
> Add paragraph about risk of spamming task docs

- content/en/apps/guides/data/csv-to-docs.md
> How to link a new record to an existing parent doc in csv-to-docs

- content/en/apps/guides/debugging/obtaining-logs.md
- content/en/apps/guides/hosting/core-developer.md
- content/en/core/guides/android/branding.md
- content/en/core/guides/android/development-setup.md
- content/en/core/guides/docker-setup.md
- content/en/core/guides/update-dependencies.md
- content/en/core/guides/using-npm.md
> remove CLI snippets use of $ 

- content/en/apps/reference/_partial_utils.md
Added definition for Utils.getField() function.
Closes #725
> add definition for Utils.getField function

- content/en/apps/reference/forms/app.md
Adds documentation for the new `add-date` XPath function being added in https://github.com/medic/cht-core/pull/7729.
> Add documentation for the `add-date` XPath function

- content/en/apps/reference/api.md
> Document sms aggregator endpoints

- content/en/apps/guides/integrations/rapidpro.md
> fixing alias so it redirects correctly

- content/en/apps/reference/translations.md
For https://github.com/medic/cht-docs/issues/778
> Add report labels to translations

- content/en/contribute/code/_index.md
Closes https://github.com/medic/cht-docs/issues/786
> Update Contributing Code page to link to Dev Setup Guide

- content/en/apps/reference/app-settings/_index.md
> Fix links to pupil documentation

- content/en/apps/guides/hosting/app-developer.md
see also [cht-core PR](https://github.com/medic/cht-core/pull/7828)
> Update App Hosting guide to work with 3.x, call out it won't work with 4.x

- content/en/apps/reference/api.md
- Correct field reference as mentioned in #807
> Correct field refrence in API reference

- content/en/apps/guides/privacy/privacy-policy.md
per [this comment](https://github.com/medic/cht-core/issues/7662#issuecomment-1272042342)
> add sample privacy policy HTML

- content/en/apps/examples/pih.md
Hi @nsitaula, Please review and approve these updates that were shared by the PIH project team. Thanks.
> PIH CHT documentation updates

- content/en/apps/reference/api.md
- content/en/contribute/code/workflow.md
- content/en/core/guides/android/releasing.md
> Remove references to Travis

- content/en/apps/guides/forms/form-inputs.md
- content/en/apps/reference/forms/app.md
For https://github.com/medic/cht-docs/issues/842
> Document `bind-id-only`

- .github/workflows/daily.yml
- content/en/apps/guides/database/couchdb-authentication.md
- content/en/apps/guides/database/database-conflicts.md
- content/en/apps/guides/integrations/rapidpro.md
> Remove sensitive words

- content/en/apps/guides/messaging/gateways/rapidpro.md
> Fix typo in rapidpro endpoint

- content/en/apps/reference/forms/app.md
> Fix broken link in demo form

- content/en/apps/guides/hosting/core-developer.md
> Fix order of instructions

- content/en/contribute/code/_index.md
Also restructures some of the text for logical flow.
For https://github.com/medic/cht-docs/issues/875
> Fixes header

- content/en/apps/tutorials/local-setup.md
> add dir hierarchy and tidy up compose up call 

- content/en/apps/reference/api.md
> Document the new "roles" property

- content/en/apps/guides/hosting/4.x/app-developer.md
https://github.com/medic/cht-core/issues/7852
> update docker helper to be current

- content/en/why-the-cht.md
Clarified with more up to date language
> Updates build once section

- content/en/apps/reference/app-settings/user-permissions.md
This adds details about the feature flag to enable the old action bar. This permission will hide More Options menu and FAB.
https://github.com/medic/cht-core/issues/7872
> Action bar - feature flag

- content/en/contribute/medic/product-development-process/_index.md
- content/en/contribute/medic/product-development-process/continuous-discovery-overview.md
Also includes related link on main process page.
> Add continuous discovery overview page

- content/en/contribute/code/core/update-dependencies.md
Includes more information about an exception when upgrading webapp's angular and a tip to fix it. Also, more information about upgrading lodash library.
> Including information about angular upgrade exception

- .github/CODEOWNERS
- Revert "Initial simple GitHub codeowners setup (#940)"
> no codeowners

- content/en/glossary.md
@mrjones-plip adding PHI and PII which have been referred to in #956
> Adding PHI and PII since they have been referred to in #956

- content/en/contribute/medic/product-core-competencies/_index.md
These were developed together as a team. We spoke about them in person in the 2023 Zanzibar meetup where everyone brought ideas, they were grouped and condensed, and put into a simple readable form, which can be seen here.
I'm adding these to the docs site, but the important point is that it wasn't just me authoring them.
> Add product team core competencies

- content/en/apps/reference/app-settings/transitions.md
~~Note that the weird `{{% tab ... %}}` stuff if just [Docsy's Tabbed Panes](https://www.docsy.dev/docs/adding-content/shortcodes/#tabbed-panes).  We don't have to use it if folks don't like it here, but seemed worth a try....~~
https://github.com/medic/cht-core/issues/7753
[cht-core PR](https://github.com/medic/cht-core/pull/7988)
> Add docs for creating user with create_user_for_contacts trans

- content/en/glossary.md
Hey @andrablaj and @garethbowen Kindly review this PR.
> Adding abbreviations to glossary

- content/en/contribute/medic/product-core-competencies/_index.md
Update _"Reliable"_ competency, from:
> Gets things done when people expect them without prompting.
to: 
> Sets and communicates clear expectations about when something needs to/will be done and does it without prompting.
> chore: Update reliable competency

- content/en/core/releases/4.1.1.md
- content/en/core/releases/_index.md
Release Notes for [4.1.1](https://github.com/medic/cht-core/issues/8116)
> chore(#8116): 4.1.1 Release Notes

- content/en/contribute/code/workflow.md
Just adding a template to use once the test is complete to provide feedback to the developers.
cc: @lorerod @ngaruko
> Add test feedback template

- content/en/apps/examples/supervisor-reference-app.md
- content/en/apps/features/supervision/_index.md
For https://github.com/medic/cht-docs/issues/985
> Cross reference Supervisor feature page and example app

- content/en/apps/reference/app-settings/transitions.md
Fixed notes that were shown in same paragraph and included Latin acronym.
For https://github.com/medic/cht-docs/issues/1006
> Updates notes

- content/en/apps/reference/_partial_cht_api.md
- content/en/apps/reference/extension-libs.md
- content/en/apps/reference/forms/app.md
> feat: add documentation for extension libs

- content/en/apps/tutorials/tasks-2.md
> fix(#1010): link format

- content/en/apps/guides/hosting/4.x/_partial_docker_directories.md
- content/en/apps/guides/tasks/pass-data-to-form.md
- content/en/apps/reference/_partial_cht_api.md
- content/en/apps/reference/_partial_utils.md
- content/en/apps/tutorials/_partial_docker_setup.md
- content/en/apps/tutorials/tasks-2.md
Removes partials from view in index summaries and related content links.
For #1008
> 1008 - Fix Partials

- .github/scripts/muffet.sh
- .github/workflows/ci.yml
- .github/workflows/daily.yml
- content/en/apps/guides/integrations/openmrs.md
- content/en/apps/guides/privacy/policy.md
- content/en/apps/tutorials/application-tests.md
- content/en/contribute/docs/workflow.md
Fix the daily build.
Closes #975
> fix(#975): Fix daily build

- content/en/apps/guides/hosting/4.x/self-hosting-multiple-nodes.md
- content/en/apps/guides/hosting/4.x/self-hosting-single-node.md
> Add wamerican to single and multi node install docs

- content/en/apps/guides/hosting/monitoring/setup.md
> Fix Grafana screenshot in monitoring setup guide

- content/en/apps/guides/hosting/4.x/data-migration.md
[Found here](https://github.com/medic/cht-docs/commit/4882ee84bf9d3f5a895ef8f1e9ef84efe11e5f49/checks) by our fancy new(ly workign) automated link checker!
> fix link to moving a shard on couchdb docs site

- content/en/apps/guides/hosting/monitoring/setup.md
closes https://github.com/medic/cht-monitoring/issues/30
> Add how to enable couch2pg postgres ingestion for CMA

- content/en/apps/guides/updates/feature-flags.md
The admin app now allows management of multiple user roles directly from the UI.  Here's the issue that added it https://github.com/medic/cht-core/issues/5903
> Update feature flags documentation 

- content/en/apps/reference/extension-libs.md
> feat: update docs for new extension libs api

- content/en/contribute/code/repository-checklist.md
Checklist to consider when creating CHT Product repositories under Medic's GitHub account.
Closes #1029
> feat(#1029): Add repository checklist

- content/en/core/overview/data-flows-for-analytics/cht-sync.md
This PR fixes left hand TOC entry from `Cht Sync` to `CHT Sync`
> fix(na) Cht Sync -> CHT Sync

- content/en/apps/guides/hosting/monitoring/setup.md
this PR removes "Grafana and Prometheus" from the top of the page
> chore(na) remove h2 title at top of page

- content/en/apps/guides/hosting/monitoring/setup.md
- content/en/core/overview/architecture.md
- content/en/core/overview/data-flows-for-analytics/cht-sync.md
- content/en/core/overview/watchdog.md
This PR: adds related content links for the architecture diagrams to each other and watchdog pages to diagrams pages
> add related links to new arch. diagrams

- content/en/core/overview/architecture.md
- content/en/core/overview/data-flows-for-analytics.md
- content/en/core/overview/data-flows-for-analytics/cht-sync.md
> fix: Fix typos in CHT Sync doc

- content/en/apps/guides/hosting/monitoring/introduction.md
- content/en/apps/guides/hosting/monitoring/production.md
- content/en/apps/guides/hosting/monitoring/setup.md
https://github.com/medic/cht-watchdog/issues/53
https://github.com/medic/cht-watchdog/pull/54
> Add docs for deleting provisioned CHT Watchdog alerts

- content/en/apps/guides/hosting/monitoring/setup.md
Closes https://github.com/medic/cht-watchdog/issues/49
> Include tip for restarting Watchdog when making config changes

- content/en/core/releases/4.1.2.md
- content/en/core/releases/_index.md
> fix: adds 4.1.2 release notes

- config.toml
Needed to use the Measurement ID, and not the Property ID
For #1058
> Uses measurement ID

- content/en/apps/guides/hosting/monitoring/setup.md
https://github.com/medic/cht-watchdog/pull/79
> Update Watchdog docs to include min version of Postgres

- content/en/apps/tutorials/local-setup.md
> Improvement: Update local-setup.md

- content/en/apps/guides/debugging/replicating-production-data-locally.md
- content/en/contribute/code/core/dev-environment.md
- content/en/contribute/code/core/using-windows.md
- content/en/contribute/docs/style-guide.md
> feat: remove grunt

- content/en/contribute/code/core/update-dependencies.md
> fix(#8494): remove lodash restriction

- content/en/core/releases/4.3.1.md
- content/en/core/releases/_index.md
> feat(#8493): add 4.3.1 release notes

- content/en/contribute/code/static-analysis.md
Adds general documentation regarding the use of SonarCloud, how it can be configured, and how to set it up on new repos.
These docs just capture my initial thoughts on how we should use Sonar. This can provide a framework for further discussion to determine how we actually want to proceed!  See https://github.com/medic/cht-core/pull/8466 for an initial repo-level configuration.
There are several org-level settings that should be discussed (and this PR seems as good as anywhere).
Since we are planning to use SonarCloud to analyze public repos, we can just use their default "Automatic" analysis method.  This will automatically analyze the default branch for the repo as well as any new PRs.
Alternatively, we could use the [GitHub Action](https://github.com/SonarSource/sonarcloud-github-action …
> feat: add SonarCloud documentation

- content/en/glossary.md
> Add Total Cost of Ownership abbreviation

- content/en/core/releases/_index.md
This adds a baseline recommended phone spec based on what we've been recommending for deployments.
> Add recommended phone specifications

- content/en/contribute/code-of-conduct.md
- content/en/contribute/medic/_index.md
- content/en/contribute/tech-radar.md
> chore(#1024): Add documentation on tech radars

- content/en/core/releases/3.17.2.md
- content/en/core/releases/4.2.4.md
- content/en/core/releases/4.3.2.md
- content/en/core/releases/4.4.1.md
- content/en/core/releases/_index.md
medic/cht-core#8593
medic/cht-core#8594
medic/cht-core#8595
medic/cht-core#8596
> Add release notes for multiple backports

- content/en/apps/guides/debugging/sharing-4x-logs.md
per CHT Core update:
* https://github.com/medic/cht-core/issues/8488
> update docs on using timeframe with docker log grabber script

- content/en/contribute/code/core/build-commands.md
> feat: add page documenting cht-core run commands

- content/en/apps/concepts/interoperability.md
> Update interoperability.md on doc site

- .github/scripts/muffet.sh
Updates Google Drive link to be ignored by the link checker. [Discussion in Slack](https://medic.slack.com/archives/CUXB9SVT5/p1698789015037749?thread_ts=1698057359.974949&cid=CUXB9SVT5).
> fix: Update link to be ignored by the link checker

- content/en/contribute/code/core/update-dependencies.md
> feat: remove wdio warning

- content/en/apps/reference/contact-page.md
> Updated definition for "reports" passed to contact-summary.templated.js

- content/en/apps/guides/performance/telemetry.md
Update [User Telemetry](https://docs.communityhealthtoolkit.org/apps/guides/performance/telemetry/) page after adding logging of [Telemetry data in Contact Edit form](https://github.com/medic/cht-core/pull/8676).
> Chore: update telemetry page

- content/en/contribute/code/android/development-setup.md
- Add the correct link and update the text to improve clarity and conciseness  
#1234 
> chore(#1234): Improve documentation clarity

- content/en/contribute/code/static-analysis.md
> fix: clarify and correct steps to set up sonar

- content/en/apps/tutorials/local-setup.md
The goal of this PR is to include Git Bash users who are using Windows without WSL.
> Improve local instance installation using VS code containers

- content/en/apps/reference/app-settings/outbound.md
Document Schedule Outbound push feature. 
Closes https://github.com/medic/cht-docs/issues/1193
> chore(#1193) Update outbound push documentation to add Schedule Outbound push feature

- content/en/contribute/code/core/automated-tests.md
- content/en/contribute/code/core/build-commands.md
Fixes from changes:
- https://github.com/medic/cht-core/issues/8706
- https://github.com/medic/cht-core/pull/8723
> fix: update build commands

- content/en/apps/guides/hosting/3.x/offline.md
The link checker [has been failing](https://github.com/medic/cht-docs/commit/03c5d16a6b8a81ba7e5fe4fa805cd908ffb15faa/checks) during the last weeks due to a missing Google Play link. This PR is removing that link from the docs. 
> fix: Remove broken Google Play link

- content/en/apps/guides/hosting/4.x/self-hosting/multiple-nodes.md
- content/en/apps/guides/hosting/4.x/self-hosting/self-hosting-k3s-multinode.md
- content/en/apps/guides/hosting/4.x/self-hosting/single-node.md
With k3s hosting documentation having been just added, this PR moves it to be next to the other self hosting docs.  As well it updates the titles so they're have parity.  Finally it adds a redirect (alias) to ensure we don't loose any traffic.
> move new k3s to be next to other self hosting, update titles to match

- content/en/core/releases/4.4.2.md
- content/en/core/releases/4.5.1.md
- content/en/core/releases/_index.md
> chore: adds release notes for 4.4.2 and 4.5.1

- content/en/apps/reference/contact-page.md
[Forum thread](https://forum.communityhealthtoolkit.org/t/is-contact-reports-limited-to-a-certain-number-of-documents/3247/3)
> feat(contact-summary): note report limit for contact-summary

- content/en/apps/concepts/access.md
> Correct grammatical error

- .github/scripts/muffet.sh
- content/en/apps/concepts/interoperability.md
- content/en/apps/reference/forms/contact.md
- content/en/apps/tutorials/localizing-cht.md
Tackles [these link errors.](https://github.com/medic/cht-docs/commit/b1b0f959843cd4a0266762c9984526388d35c723/checks) 
> fix: Fix broken links

- content/en/apps/examples/pih.md
Change the mention of MNCH app under Resources to integrated CHT application.
> Change mention of of only MNCH CHT app to integrated

- content/en/contribute/code/workflow.md
> fix: document adding issue to milestone

- content/en/apps/reference/app-settings/outbound.md
Update the cron example in the outbound push docs section
> docs(#1272): update cron example

- content/en/apps/guides/data/users-bulk-load.md
> Change from HTML to markdown

- content/en/contribute/code/core/dev-environment.md
Updates the steps for local dev setup
> chore: update steps for local dev setup

- content/en/contribute/tech-radar.md
Enhance Technology Radar content. 
> chore: Update Tech Radar content

- content/en/apps/guides/hosting/4.x/app-developer.md
Adds a how to use `DEBUG` flag per #8293
> chore(#8293): Add debug flag for docker helper

- content/en/contribute/code/core/dev-environment.md
Correct CouchDB environment variables per [this Forum discussion](https://forum.communityhealthtoolkit.org/t/couchdb-installation-issue-on-apple-silicon-chip/3205/35). 
> fix: Fix CouchDB env variables

- config.toml
[description]
medic/cht-core#7993
> fix: document node 20 and nvm 10

- content/en/apps/guides/hosting/4.x/app-developer.md
Add Docker Helper Troubleshooting section with the guidelines from [medic/cht-core/issues/8612](https://github.com/medic/cht-core/issues/8612).
> chore: Add troubleshooting to Docker Helper guide

- content/en/core/releases/4.5.2.md
- content/en/core/releases/_index.md
https://github.com/medic/cht-core/issues/8848
This includes the ticket from [this milestone](https://github.com/medic/cht-core/milestone/126)
> chore: release notes 4.5.2

- content/en/contribute/code/static-analysis.md
> chore: document how to turn off PR comments

- content/en/apps/guides/security/securely-onboarding-users-at-scale.md
Add a doc for secure user management at scale per #1281
> feat(#1281): Add a doc for secure user management at scale

- content/en/contribute/medic/onboarding/all-the-things.md
Add CHT Watchdog clarification to All the Things.
> chore: Add clarifications to All The Things

- content/en/apps/reference/api.md
> feat: document `/api/v2/export/user-devices`

- README.md
- troubleshooting.md
this PR adds a work around for how to downgrade `hugo` and optionally install `go`
> fix (#1302): Update troubleshooting steps for hugo "key kind not allowed" error

- content/en/contribute/medic/onboarding/team-meetings.md
Describe why and how the Product Team does regular team calls. This includes how teammates should facilitate them.
> Add Product Team monthly meeting howto

- content/en/core/releases/4.6.0.md
- content/en/core/releases/_index.md
https://github.com/medic/cht-core/issues/8823
> feat: add cht-core 4.6.0 release notes

- content/en/apps/guides/integrations/rapidpro.md
> fix(na): fix 404 to textit blog

- content/en/apps/guides/data/analytics/environment-variables.md
- content/en/apps/guides/data/analytics/production.md
> chore(#1297): Add production considerations for CHT Sync

- content/en/apps/guides/database/querying_apdex_telemetry.md
https://github.com/medic/care-teams/issues/63
> chore(#63): documents query to count apdex in a date range

- .github/scripts/muffet.sh
- content/en/apps/guides/data/analytics/production.md
Exclude private repo links. Fix typo. [Related failed build](https://github.com/medic/cht-docs/commit/ed2a0081fbd6e5cc38be124f91415b42de27b4f9/checks).
> fix: Exclude private repo links from link checker

- content/en/core/overview/cht-sync.md
> chore(#1336): Remove dataemon repo mentions

- content/en/apps/reference/forms/app.md
https://github.com/medic/cht-core/issues/8971
> feat: add docs for new XPath date functions

- content/en/contribute/code/core/deploy-on-eks.md
Updated `deploy-on-eks.md` with additional helpful information when starting the deployment.
> Update deploy-on-eks.md with additional helpful information when starting the deployment

- content/en/contribute/medic/onboarding/daily-updates.md
- content/en/contribute/medic/onboarding/team-meetings.md
Create handbook page for Product Team daily updates.
> chore: Create handbook page for daily updates

- content/en/contribute/code/core/deploy-on-eks.md
list out explicit changes needed to `values.yaml` . Prior steps were incomplete and vague.
> fix(na): list out explicit changes needed to `values.yaml` for EKS setup

- assets/scss/_variables_project.scss
- content/en/_index.md
- content/en/apps/reference/_index.md
> fix(#1343): reduce unnecessary header content on mobile

- content/en/apps/reference/api.md
Issue: medic/cht-core#8877
Code PR: medic/cht-core#8928
> feat: Document looking up users from their `facility_id` or `contact_id`

- content/en/apps/reference/api.md
https://github.com/medic/cht-core/issues/8986
https://github.com/medic/cht-core/pull/9016
> feat: add API docs for getting user by username

- content/en/apps/reference/contact-page.md
- content/en/contribute/medic/onboarding/daily-updates.md
1. Update Contact Summary documentation following the [increase of number of docs from 50 to 500](https://github.com/medic/cht-core/pull/8984)
2. Fix typo in Daily Updates page
> Update contact summary documentation

- content/en/apps/guides/hosting/4.x/adding-tls-certificates.md
- content/en/apps/guides/hosting/4.x/self-hosting/multiple-nodes.md
- content/en/apps/guides/hosting/4.x/self-hosting/single-node.md
Supports code merged for issue [#8591](https://github.com/medic/cht-core/issues/8591) and should close the issue.
cc @garethbowen
> chore(#8591): add docs for optional proxy configuration

- content/en/apps/guides/android/branding.md
closes https://github.com/medic/cht-docs/issues/1369
> Advice to change OS language to English

- content/en/contribute/code/core/automated-tests.md
closes https://github.com/medic/cht-docs/issues/1376
> Clarifying test types and expectations

- content/en/apps/guides/android/publishing.md
- content/en/contribute/code/android/releasing.md
Add some necessary steps and clarification I faced when releasing `cht-android`.
> Add some extra steps and clarification for easier understanding of release process for cht-android

- content/en/core/releases/4.7.0.md
- content/en/core/releases/4.7.1.md
- content/en/core/releases/_index.md
> chore: adds 4.7.1 release notes

- content/en/contribute/code/design-docs.md
- content/en/contribute/code/repository-checklist.md
- content/en/contribute/code/static-analysis.md
- content/en/contribute/code/using-npm.md
> chore(#1385): Create design docs guidelines

- content/en/hosting/monitoring/setup.md
update sql exporter docs to use new format per medic/cht-watchdog/issues/107
> fix(na): update sql exporter docs to use new format

- content/en/contribute/code/core/automated-tests.md
Update `wdio.conf` paths per [failing GitHub Action](https://github.com/medic/cht-docs/commit/19ac8babe16df6158f413c87536f994aef465d1c/checks). 
> chore: Update wdio conf paths

- content/en/apps/concepts/hierarchy.md
> fix(#1400): Fix Mermaid diagrams

- content/en/glossary.md
per [link checker resutls](https://github.com/medic/cht-docs/commit/bc31562fb8f060ac288592f728b4f0b1b94043c9/checks)
> fix broken link to WHO PDF

- content/en/apps/reference/api.md
https://github.com/medic/cht-core/issues/9065
Code changes in these PRs:
https://github.com/medic/cht-core/pull/9090
https://github.com/medic/cht-core/pull/9176
> feat(#9065): add api doc for getting person by UUID

- content/en/core/releases/4.7.2.md
- content/en/core/releases/4.8.1.md
- content/en/core/releases/_index.md
> chore: adds release notes for 4.7.2 and 4.8.1

- content/en/contribute/medic/onboarding/daily-updates.md
Update dailies channel name from _#dailies_ to _#product-dailies_
> chore: Update dailies channel name from #dailies to #product-dailies

- content/en/core/releases/4.7.2.md
- content/en/core/releases/4.8.1.md
> Updates 4.8.1 and 4.7.2 release notes with new issues

- content/en/apps/guides/data/analytics/setup.md
Per [this comment](https://github.com/medic/cht-docs/pull/1429#issuecomment-2181071664), this PR removes unnecessary `npm ci` command from the instructions. 
> chore(#1405): Remove useless command

- content/en/contribute/code/core/automated-tests.md
Add reference links to cht-core files
> chore: Add reference links to cht-core files

- content/en/apps/tutorials/user-management-tool.md
> User management tool configuration

- content/en/apps/guides/android/publishing.md
- content/en/apps/guides/updates/preparing-for-4.md
- content/en/contribute/code/core/dev-environment.md
To fix concern raised on grep results when doing hosting moving, for aliases. - https://github.com/medic/cht-docs/pull/1361
This fixes this issue raised - https://github.com/medic/cht-docs/issues/1373
> Fix grep results for aliases

- content/en/contribute/medic/product-development-process/product-trio/product-trio-activities.md
update trio activities 
closes #1425
> feat (#1425): update trio activities 

- content/en/hosting/_index.md
- content/en/hosting/requirements.md
update hosting requirements and considerations per feedback
> chore(na): update hosting requirements and considerations per feedback

- .github/scripts/muffet.sh
- content/en/contribute/code/static-analysis.md
- content/en/core/overview/translations.md
Exclude and update broken links per [failed action](https://github.com/medic/cht-docs/commit/7e013713862005a8e55b21a27197a2c7bc7c8f5a/checks).
[POE-related code was removed recently](https://github.com/medic/cht-core/commit/2d0be93d49acdd44312100499d47a1d75653fbd5). 
> chore: Update broken links

- content/en/core/releases/4.9.0.md
vanity change `MrJones` -> `mrjones` ;)
> vanity change MrJones -> mrjones ;)

- content/en/contribute/docs/style-guide.md
- content/en/core/overview/translations.md
https://github.com/medic/cht-core/issues/9172
> fix: update documentation on managing translations

- content/en/apps/reference/forms/app.md
medic/cht-core#9227
[description]
> feat: add documentation for luhn xpath function

- content/en/hosting/4.x/app-developer.md
> chore(#X): add error keyword to troubleshooting guide for core starter

- content/en/contribute/medic/product-development-process/focused-groups.md
Housekeeping, removes roles that are no longer active in the Infrastructure FWG
> chore: Update Infrastructure FWG roles

- content/en/apps/tutorials/user-management-tool.md
> Introductory section of the user management tool

- content/en/contribute/code/core/automated-tests.md
Updates upgrade e2e documentation
> chore: update upgrade e2e documentation

- content/en/apps/guides/data/analytics/production.md
Add instructions on deploying cht-sync to production using helm and kubernetes
> docs: add instructions on deploying cht-sync to production

- assets/scss/main.scss
- layouts/_default/_markup/render-heading.html
Fixes [the issue on Heading self links](https://github.com/medic/cht-docs/issues/1486) missing after upgrade.
> Adding heading self link

- content/en/core/releases/_index.md
Mark 4.6.x as EOL in the https://docs.communityhealthtoolkit.org/core/releases/ page.
> chore: mark release 4.6.x as EOL in the releases page

- content/en/apps/guides/data/analytics/production.md
Update cht sync docs to add a step to clone the repo
> Update cht sync docs to add a step to clone the repo

- content/en/contribute/code/style-guide.md
Document preference for ts over js
> chore: document preference for ts over js

- content/en/apps/guides/training/training-cards-resources/_index.md
specify when/how to use images a bit more explicitly on training cards
> specify when/how to use images a bit more explicitly

- content/en/apps/reference/forms/app.md
https://github.com/medic/cht-core/issues/6390
https://github.com/medic/cht-core/pull/9340
> feat(#6390): add docs about the phone widget

- content/en/apps/examples/anc.md
- content/en/contribute/code/repository-checklist.md
- content/en/hosting/3.x/self-hosting.md
per [muffet link check](https://github.com/medic/cht-docs/commit/7d1152fdabdf833625ba62bec34a0b4767a47f17/checks):
* Fix link to docker compose overview 
* Fix link to MS Eng Fundamentals
* update link to WHO core health indicators (use index)
> Fix link to docker compose overview per muffet

- content/en/apps/reference/api.md
Issue: https://github.com/medic/cht-core/issues/9193
Code changes: https://github.com/medic/cht-core/pull/9311
> feat: add API Doc for getting people by type

- content/en/apps/reference/api.md
Issue: https://github.com/medic/cht-core/issues/9193
Code changes: https://github.com/medic/cht-core/pull/9368
> feat: add API doc for getting places by type

- content/en/apps/guides/data/analytics/environment-variables.md
> chore(#1513): remove outdated CHT Sync environment variables

- content/en/contribute/code/workflow.md
- clarity of including QA as reviewers
- clarify the importance of documentation as part of the development process
- Emphasis when a work is considered complete (ie, docs and test coverage are part of the process to completion). 
- suggests self-code reviews as best practices 
> chore: clarify pull request process

- content/en/hosting/monitoring/setup.md
Repurpose the CHT Watchdog setup instructions for CHT Sync.
#1510 
> docs: add instructions for connecting CHT Watchdog to CHT Sync

- content/en/apps/guides/data/analytics/introduction.md
- content/en/apps/guides/data/analytics/production.md
- content/en/core/overview/cht-sync.md
Formatting. Removing Medic mentions.
> chore: Cleanup data pipeline pages

- content/en/apps/guides/data/analytics/setup.md
docker-compose -> docker compose as `docker-compose` is now deprecated and we're moving to use the [non-deprecated one](https://github.com/medic/cht-core/issues/8781).
> docker-compose -> docker compose

- content/en/apps/guides/data/analytics/_index.html
- content/en/apps/guides/data/analytics/environment-variables.md
- content/en/apps/guides/data/analytics/introduction.md
- content/en/apps/guides/data/analytics/production.md
- content/en/apps/guides/data/analytics/testing-dbt-models.md
- content/en/contribute/code/hall-of-fame.md
- content/en/core/overview/cht-sync.md
> chore(#1521): remove CHT Pipeline mentions

- content/en/building/guides/data/analytics/setup.md
Remove section about Run all CHT Sync services locally. See this [conversation](https://github.com/medic/cht-sync/pull/149#issuecomment-2343437097) for more context
> docs: remove 'Run all CHT Sync services locally' section

- content/en/building/guides/data/analytics/setup.md
Update the text in the cleanup section
> fix: update link text in cleanup section

- content/en/building/guides/data/users-bulk-load.md
#846 
Document how to use the bulk user upload spreadsheet with custom places types
> feat(#846): bulk user upload spreadsheet with custom places types

- content/en/building/concepts/hierarchy.md
- content/en/building/concepts/interoperability.md
Fixes [this](https://github.com/medic/cht-docs/issues/1547) issue
> Remove /n in mermaid charts

- content/en/building/concepts/_index.md
- content/en/building/examples/anc.md
- content/en/building/examples/pharmacovigilance-reference-app.md
- content/en/building/examples/pih.md
- content/en/building/features/admin/_index.md
- content/en/building/local-setup.md
- content/en/building/prerequisites.md
- content/en/building/tutorials/app-forms.md
- content/en/building/tutorials/application-graphics.md
- content/en/building/tutorials/application-settings.md
- content/en/building/tutorials/application-tests.md
- content/en/building/tutorials/condition-cards.md
- content/en/building/tutorials/contact-and-users-1.md
- content/en/building/tutorials/contact-and-users-2.md
- content/en/building/tutorials/contact-summary.md
- content/en/building/tutorials/couch2pg-setup.md
- content/en/building/tutorials/form-properties.md
- content/en/building/tutorials/localizing-cht.md
- content/en/building/tutorials/sms-forms.md
- content/en/building/tutorials/targets.md
- content/en/hosting/3.x/_index.md
- content/en/hosting/3.x/ssl-cert-install.md
- content/en/hosting/4.x/_index.md
[This](https://docs.google.com/document/d/1Vnq3HgXDQxtiHi4m3UJORnUzB1dj5H4wfxt1Q4kIEgQ/edit#heading=h.smca4jwqayex) is the vision. This PR migrates pre-requisites and getting started to top level navigation.
> Another set of building section migration

- content/en/contribute/code/core/apdex-automation-tests.md
[#179](https://github.com/medic/care-teams/issues/179)
> chore(#179):update cht-docs with apdex automation tests set-up

- content/en/hosting/3.x/_index.md
- content/en/hosting/4.x/_index.md
- content/en/hosting/4.x/adding-tls-certificates.md
- content/en/hosting/4.x/app-developer.md
- content/en/hosting/4.x/backups.md
- content/en/hosting/4.x/data-migration.md
- content/en/hosting/4.x/logs.md
- content/en/hosting/4.x/self-hosting/_index.md
- content/en/hosting/kubernetes-vs-docker.md
- content/en/hosting/monitoring/_index.html
- content/en/hosting/vertical-vs-horizontal.md
To make weighting of new pages under the hosting section easy. Removal of abstract values.
> Fix hosting pages weighting 

- content/en/core/releases/4.11.0.md
- content/en/core/releases/_index.md
> release: add 4.11.0 release notes

- content/en/core/releases/4.9.0.md
> fix: include additional bug fix in 4.9.0 release

- content/en/contribute/code/workflow.md
> chore(#1517): Reshuffle development workflow to match dev journey

- content/en/hosting/costs/_index.md
specify self hosted vs medic hosted - per input from @Marina-Kenf who wanted a specific MoH to have clarity on target audience of this doc.
> specify self hosted vs medic hosted

- content/en/contribute/medic/onboarding/all-the-things.md
- content/en/contribute/medic/onboarding/product-team.md
- content/en/contribute/medic/onboarding/team-meetings.md
- content/en/contribute/medic/onboarding/technical-resources.md
- content/en/contribute/medic/product-development-process/focused-groups.md
Cleanup Product Team pages. Remove Infra FWG mentions. 
> chore: Cleanup product team pages

- content/en/building/local-setup.md
Fixes issue https://github.com/medic/cht-docs/issues/1558
> Update pyxform command

- content/en/hosting/vertical-vs-horizontal.md
fix vert vs horz scaled diagrams 
closes #1573
> fix(#1573): vert vs horz scaled diagrams

- content/en/design/components/_index.md
This fixes the issue described here https://github.com/medic/cht-docs/issues/1560
> Fix codepen visuals

- content/en/building/guides/data/analytics/production.md
Add instructions on how to estimate Postgres size.
https://github.com/medic/cht-sync/issues/85
> docs: add instructions on how to estimate required Postgres disk size

- content/en/core/overview/test-data-generator.md
The Test Data Generator has been around for 1 year and more teams are using it. Adding it here will make it easier to discover for others. 
> chore: add test data generator tool documentation

- content/en/building/concepts/interoperability.md
- content/en/building/guides/integrations/fhir.md
> feat(#1555): interoperability guide

- content/en/building/guides/data/analytics/production.md
> fix(#1562): changing command and wording for clarity

- content/en/hosting/costs/_index.md
Adds example of k8s deployment on EC2 hardware with EBS storage 
closes #1528
> chore(#1528): example for small k8s deployment

- content/en/building/guides/integrations/fhir.md
- content/en/building/guides/integrations/openmrs.md
Per [failing link checker](https://github.com/medic/cht-docs/commit/c0483659afe75167b8ad1fe8b48bea44ffd063e8/checks).
> chore: Fix broken links

- .github/scripts/muffet.sh
- .github/workflows/cron-check-links.yml
Reverting [these changes](https://github.com/medic/cht-docs/pull/1598/files), but keeping the links to catch "fresh" broken ones. 
> chore: downgrade muffet

- content/en/building/features/training/_index.md
- content/en/building/guides/training/training-cards/_index.md
Documents this feature https://github.com/medic/cht-core/issues/9488
> chore: updates doc about training cards opening once a day

- content/en/hosting/4.x/production/_index.md
fix links to single & multi-node on 4.x prod hosting
closes #1614
> fix(#1614): fix links to single & multi-node on 4.x prod hosting

- content/en/contribute/medic/onboarding/technical-resources.md
Update onboarding technical resources. Remove Medic mentions. Intentionally keep the cht-dev-workshop Slack channel mention, so that external contributors reach out and join. 
> chore: update onboarding technical resources

- content/en/building/reference/app-settings/_index.md
medic/cht-core#9416
Copies the relevant sections from the pupil readme which is being deleted.
Cleans up a few rendering errors.
medic/cht-core#9416
> chore: inline pupil documentation

- content/en/building/guides/database/querying_training_card_telemetry.md
<details>
<summary>Total number of users who have viewed a particular training set</summary>
https://github.com/user-attachments/assets/74b0ab26-c83d-42b6-8701-5098578ecd2a
</details>
<details>
<summary>How many times each user has viewed but not completed the training</summary>
https://github.com/user-attachments/assets/2c392e1c-7402-44c0-9be3-4b95022fec96
</details>
<details>
<summary>Number of times each user has viewed a particular training set</summary>
https://github.com/user-attachments/assets/9549211d-a39a-4331-805b-5d334c20b702
</details>
<details>
<summary>How many times each user quit a particular training set</summary>
https://github.com/user-attachments/assets/9c613da2-f8f6-4a20-89aa-21e996dde42a
</details>
<details>
<summary>List of users who have completed a particular …
> feat(#1620): add training card sql queries

- content/en/hosting/monitoring/setup.md
> docs: update setup instructions for CHT Watchdog on CHT Sync to clarify target naming

- content/en/design/external-resources/_index.md
Adding external resources (links to material, google fonts, forum) to the design section
> External resources

- content/en/hosting/analytics/_index.md
- content/en/hosting/analytics/building-dbt-models.md
- content/en/hosting/analytics/couch2pg-to-cht-sync-migration.md
- content/en/hosting/analytics/environment-variables.md
- content/en/hosting/analytics/setup-docker-compose.md
- content/en/hosting/analytics/setup-kubernetes.md
- content/en/hosting/analytics/testing-dbt-models.md
Add aliases to CHT Sync pages to avoid broken links. 
> chore: add aliases to cht sync pages

- content/en/building/training/training-cards/training-cards-configuration.md
Simplify page title per my own [comment](https://github.com/medic/cht-docs/pull/1647#pullrequestreview-2388580598).
> chore: simplify training cards config title

- content/en/hosting/analytics/setup-docker-compose.md
Add comment about correct port for production CHT Core deployments
closes medic/cht-sync/issues/175
> fix(na):  specify correct port for production CHT Core deployments

- content/en/building/guides/tasks/pass-data-to-form.md
- content/en/building/tasks/complex-tasks.md
Closes https://github.com/medic/cht-docs/issues/1646
> Move complex task file for grouping

- content/en/core/releases/4.12.0.md
These notes include issues that weren't fixed in this release, possibly because the release notes weren't generated before all unresolved issues were moved to the next release.
> fix: remove issues that weren't closed in this release

- content/en/building/reference/app-settings/_index.md
medic/cht-core#8806
[description]
> fix: update rule configuration docs for bug fix

- content/en/contribute/code/core/dev-environment.md
Per failed GA:
```
Run ./.github/scripts/muffet.sh
http://localhost:1313/contribute/code/core/dev-environment/
404	http://www.sagehill.net/docbookxsl/InstallingAProcessor.html
http://localhost:1313/contribute/code/releasing/publish-docker-image/
too many redirections	https://hub.docker.com/orgs/medicmobile/repositories
Error: Process completed with exit code 1.
```
> chore: update install url

- content/en/building/tasks/overview.md
Fixes https://github.com/medic/cht-docs/issues/1664
> Decision support link fix

- content/en/building/local-setup.md
- content/en/building/tutorials/couch2pg-setup.md
- content/en/contribute/code/core/automated-tests.md
- content/en/contribute/code/core/dev-environment.md
- content/en/hosting/3.x/_index.md
- content/en/hosting/3.x/app-developer.md
- content/en/hosting/3.x/self-hosting.md
- content/en/hosting/3.x/ssl-cert-install.md
- content/en/hosting/4.x/_index.md
- content/en/hosting/4.x/data-migration.md
per #medic/cht-core/issues/8781
> chore(): remove use of docker-compose command    

- content/en/contribute/medic/product-development-process/deploy-on-eks.md
update Medic EKS docs for multi-node by adding a tabbed interface on step 3: 
[Screencast from 2024-11-01 10-44-13.webm](https://github.com/user-attachments/assets/33999598-a540-46d1-9228-349f53d83bb8)
> feat(na): update Medic EKS docs for multi-node

- content/en/hosting/monitoring/setup.md
Add missing alias for CHT Watchdog doc
Related: https://github.com/medic/cht-watchdog/pull/127
> chore: add missing alias for CHT Watchdog doc

- content/en/building/concepts/care-guides.md
- content/en/building/contact-management/contacts.md
- content/en/building/contact-summary/_index.md
- content/en/building/contact-summary/contact-summary-overview.md
- content/en/building/contact-summary/contact-summary-templated.md
- content/en/building/guides/forms/form-inputs.md
- content/en/building/guides/integrations/oppia.md
- content/en/building/reference/extension-libs.md
- content/en/building/reference/forms/app.md
- content/en/building/tutorials/application-tests.md
- content/en/building/tutorials/condition-cards.md
- content/en/building/tutorials/death-reporting.md
- content/en/core/overview/db-schema.md
Closes https://github.com/medic/cht-docs/issues/1679
> Migrate contact summary

- content/en/core/releases/4.14.0.md
- content/en/core/releases/_index.md
This PR adds the release notes for `4.14.0`
> release: add 4.14.0 release notes

- content/en/building/condition-cards.md
- content/en/building/tutorials/application-tests.md
Closes https://github.com/medic/cht-docs/issues/1680
> Move condition cards section

- content/en/building/_index.md
- content/en/building/prerequisites.md
Avoids duplication in building index page and prerequisites page.
> Building pre-requisites section consolidation

- hugo.toml
[description]
medic/cht-core#9636
> fix: update recommended node version to 22

- content/en/contribute/code/releasing/publish-docker-image.md
fix infinite redirect in [muffet link checker](https://github.com/medic/cht-docs/commit/7afc4b7fc87d9d3c464a46be4b8611e313dc77a6/checks) for docker org
> fix infinite redirect in muffet link checker for docker org

- content/en/contribute/code/core/style-guide-automated-e2e-tests.md
After the clean-up work, we define the structure that the e2e test should follow, which needs to be updated in the documentation
[cht-core #9578](https://github.com/medic/cht-core/issues/9578)
> chore(#9578): add desire structure for the e2e tests files

- content/en/contribute/code/core/style-guide-automated-e2e-tests.md
- content/en/glossary.md
add k3s, k3d, kubernetes to glossary, link to same from e2e page
> feat(na): add k3s, k3d, kubernetes to glossary, link to same from e2e page

- content/en/contribute/code/core/dev-environment.md
…
two quick fixes:
* remove version from compose file
* always use same username password for couch
> fix(na): remove version from compose file, always use same username password for couch

- content/en/building/translations/managing-translations.md
link to list of language codes instead of list of country codes
> fix(na): link to list of language codes instead of list of country codes

- content/en/contribute/medic/product-development-process/deploy-on-eks.md
This PR:
* ensures both `node` >22 and `npm` are installed
* instructs users to run `npm install` so that dependencies are installed
> Update CHT Deploy docs to include node

- content/en/building/reference/extension-libs.md
https://forum.communityhealthtoolkit.org/t/formatting-questions-and-the-user-interface-with-javascript/4578
> feat: add link to blog post regarding advanced extension-libs usage

- content/en/hosting/4.x/migration/_index.md
add link to bad shard [forum post](https://forum.communityhealthtoolkit.org/t/restoring-corrupted-couchdb-database/4551/1) on [migration page](https://docs.communityhealthtoolkit.org/hosting/4.x/migration/)
> fix(na): add link to bad shard forum post

- content/en/contribute/code/core/dev-environment.md
we [now use](https://github.com/medic/cht-core/issues/6537) python3 instead of 2! 
> chore(na): update app dev to use python3

- content/en/contribute/code/core/update-dependencies.md
Just cleaning up our documented procedure for upgrading dependencies in cht-core so that it is up-to-date!
> feat: updates docs for upgrading cht-core dependencies

- content/en/exploring/interoperability.md
Fix broken GA:
>hugo: collected modules in 11570 ms
Start building sites … 
hugo v0.122.0-b9a03bd59d5f71a529acb3e33f995e0ef332b3aa+extended linux/amd[64](https://github.com/medic/cht-docs/actions/runs/13120848988/job/36606176178#step:6:65) BuildDate=2024-01-26T15:54:24Z VendorInfo=gohugoio
ERROR [en] REF_NOT_FOUND: Ref "building/guides/interoperability/": "/home/runner/work/cht-docs/cht-docs/content/en/exploring/interoperability.md:21:316": page not found
ERROR [relatedContent] REF_NOT_FOUND: Ref "building/guides/interoperability": "exploring/interoperability.md": page not found
Total in 22701 ms
Error: error building site: logged 2 error(s)
> fix: update broken link

- content/en/contribute/technical-resources.md
Remove the mentions of dev workshop. New events and discussion forums coming soon ✨ 
> chore: remove dev workshop

- content/en/core/releases/4.17.0.md
- content/en/core/releases/_index.md
> chore: add 4.17.0 release notes

- content/en/contribute/code/cht-conf.md
Add a note for cht-conf on obtaining a session token for session-based authentication.
> chore: update cht-conf.md

- content/en/hosting/analytics/building-dbt-models.md
- content/en/hosting/analytics/setup-docker-compose.md
Just noticed a small typo in the example `cht_form_model` dbt config.  
Then, I made a minor docs edit to the cht-sync setup guide for more clarity on what needs configured.
> fix: update dbt example code to fix typo

- content/en/contribute/code/repository-checklist.md
Update docs for configuring a new repo to include config we missed on `eslint-config` when setting up CI/CD.
> feat: update new repo docs to configure medic-ci bot

- content/en/_index.md
Update the docs site homepage to match the names of the new docs site sections. 
> chore: update homepage

- content/en/building/integrations/android.md
- content/en/building/integrations/rapidpro.md
- content/en/core/releases/4.7.0.md
Fix 404s per last link checker output:
```
Run chmod +x ./.github/scripts/*muffet*
http://localhost:1313/building/integrations/android/
404	http://localhost:1313/guides/android/branding/android-12-prompt.png
http://localhost:1313/building/integrations/rapidpro/
404	https://app.rapidpro.io/video/
http://localhost:[13](https://github.com/medic/cht-docs/commit/61e36c42468a0fcb244efe85a2ecde3047b63709/checks#step:7:14)13/core/releases/4.7.0/
404	https://github.com/1yrr
Error: Process completed with exit code 1.
```
> fix: fix 404s

- content/en/building/integrations/android.md
Fix `404` captured by the weekly link checker: 
```
http://localhost:1313/building/integrations/android/
404	http://localhost:1313/building/integrations/guides/android/branding/android-[12](https://github.com/medic/cht-docs/commit/724c1bfd1b7e4ef19935ee895343337490518210/checks#step:7:13)-prompt.png
```
> fix: update image link to fix 404

- content/en/building/reference/api.md
Add documentation for new REST endpoints for Contacts and Reports.
Solves: https://github.com/medic/cht-core/issues/9798
> feat: add docs for new contact and report REST endpoints

- content/en/building/reference/api.md
- content/en/core/releases/4.18.0.md
Just added a bit more to the release docs about  the new REST endpoints for getting contact/report data (including links to the fresh new API docs)!
> feat: add new REST endpoints to 4.18.0 release docs

- content/en/building/contact-management/user-management-tool.md
Fix the internal fragment/hash links
Fixing some internal links that are not working by:
- changing all uppercase letters in the identifiers to lowercase
> fix(#1799): internal links not working

- content/en/_index.md
Remove top half of homepage to make it more lean per docs squad and per #1792
> fix(#1792): Update homepage 

- content/en/building/messaging/gateways/africas-talking.md
Corrects Africa's Talking docs to show how to correctly store the credentials for `africastalking.com:incoming` and `africastalking.com:outgoing`
Closes #1797 
> chore(#1797): update africa's talking documentation

- content/en/hosting/4.x/app-developer.md
This adds a few multitabs for splitting the [manual developer install to support](https://docs.communityhealthtoolkit.org/hosting/4.x/app-developer/#manual-docker-compose-method) both single and multi-node
per https://github.com/medic/cht-core/issues/9863
> feat(na): Add support for dev multi-node

- content/en/contribute/code/static-analysis.md
Per failing link checker:
>Run chmod +x ./.github/scripts/*muffet*
http://localhost:1313/contribute/code/static-analysis/
404	https://docs.sonarsource.com/sonarqube/latest/project-administration/analysis-scope/
404	https://docs.sonarsource.com/sonarqube/latest/project-administration/analysis-scope/#ignoring-blocks-within-files
Error: Process completed with exit code **1.**
> chore: update sonar links sending 404

- content/en/building/forms/configuring/additional-docs.md
Removed an unnecessary description line from the file.
Resolves #1126
> chore(#1126): remove inaccurate description line 

- content/en/hosting/couch2pg/_index.md
- content/en/hosting/couch2pg/migration.md
- content/en/hosting/couch2pg/setup-and-devlopment.md
This PR:
* moves  [couch2pg readme](https://github.com/medic/cht-couch2pg/blob/main/README.md) from GH to CHT Docs. Also see [related couch2pg PR](https://github.com/medic/cht-couch2pg/pull/150)
* adds new doc on how to migrate couch2pg + postgres data from one server to another
per #1806
> feat(#1806): couch2pg readme and migration guide

- content/en/glossary.md
Add items to the glossary. Change the style of entries to increase readability.
> chore: add to glossary and change format

- content/en/core/releases/3.8.0.md
- content/en/hosting/4.x/production/kubernetes/gcp-multinode.md
Per failing link checker:
```
Run chmod +x ./.github/scripts/*muffet*
http://localhost:1313/contribute/docs/workflow/
403	https://github.com/
http://localhost:1313/hosting/4.x/production/kubernetes/gcp-multinode/
404	http://localhost:1313/hosting/4.x/production/kubernetes/docker
http://localhost:[13](https://github.com/medic/cht-docs/commit/78a8552eac8607286ba349d4bac059a33bf41bdc/checks#step:7:14)13/core/releases/3.8.0/
503	https://docs.communityhealthtoolkit.org/apps/
Error: Process completed with exit code 1.
```
> fix: fix 404

- content/en/design/interface/ui-kit.md
Move Figma files to Medic Figma account. 
> chore: update figma files location

- content/en/community/contributing/first-time-contributors.md
Add some extra notes that might be helpful to first-time contributors in the first-time contributor guide.
> chore(na): add some extra notes to the first time contributor guide

- content/en/community/_index.md
add link to [academy](https://academy.communityhealthtoolkit.org/)  to the [community page](https://docs.communityhealthtoolkit.org/community/)
> add academy link to community page

- content/en/community/contributing/code/static-analysis.md
Per link checker:
```
http://localhost:1313/community/contributing/code/static-analysis/
404	https://docs.sonarsource.com/sonarqube/latest/user-guide/metric-definitions/
```
> fix: update broken Sonar link

- content/en/community/contributing/code/core/dev-environment.md
[description]
add bzip to prereqs on core dev setup page
see [forum discussion on same](https://forum.communityhealthtoolkit.org/t/unable-to-setup-cht-core-dev-environment/4919)
> fix(na) add bzip to prereqs on core dev setup page

- content/en/community/contributing/code-of-conduct.md
- content/en/community/contributing/code/creating-good-first-issues.md
- content/en/community/contributing/creating-good-first-issues.md
- content/en/community/contributing/first-time-contributors.md
- content/en/community/contributing/technical-resources.md
This PR creates a new page describing how to create a good first issue ticket.  
> feat(na): good first issue instructions and example ticket

- content/en/community/contributing/code/core/dev-environment.md
remove legacy deps per @jkuester 
> fix(na): remove legacy deps

- content/en/community/contributing/code/static-analysis.md
This PR:
* changes `eslint` to `ESLint`
* adds information on how to run `npm run lint`, which didn't exist in docs before
Related:
* [forum post](https://forum.communityhealthtoolkit.org/t/how-to-lint-on-the-command-line/4939/2)
* `cp`  [refactor PR](https://github.com/medic/cht-core/pull/9939)
> fix(na): add cli linting steps

- content/en/community/contributing/code/core/dev-environment.md
this PR adds  ram, cpu and disk requirements to [core dev](https://docs.communityhealthtoolkit.org/community/contributing/code/core/dev-environment/) page, per #1838
> fix(#1838): add core dev ram, cpu and disk requirements

- content/en/community/_index.md
- content/en/community/contributing/_index.md
- content/en/community/hall-of-fame.md
- content/en/community/roadmap.md
- content/en/community/tech-radar.md
Change card link to the newly created roadmap page. 
> chore: update link for roadmap

- .github/scripts/muffet.sh
- content/en/building/guides/debugging/secure-sharing-of-developer-instance.md
- content/en/building/interoperability/openmrs.md
- content/en/building/messaging/gateways/rapidpro.md
- content/en/building/targets/targets-js.md
- content/en/releases/2_16_0.md
- content/en/releases/4_4_0.md
This PR fixes 404s and 429s by fixing the links to images (404) and slows down muffet (429) per this [slack alert from muffet](https://github.com/medic/cht-docs/commit/89de1514b2c35f463070d7dac53a66d147ade172/checks).
> fix(na): slow down muffet, fix 404s

- content/en/building/integrations/rapidpro.md
- content/en/community/contributing/code/core/dev-environment.md
- content/en/hosting/3.x/app-developer.md
- content/en/hosting/4.x/docker/backups.md
- content/en/hosting/4.x/kubernetes/self-hosting-k3s-multinode.md
- content/en/hosting/monitoring/production.md
The "Medic recommends" sentences are irrelevant. The recommendations on the docs site should be community-driven, generic, and data-driven. This PR removed the "Medic recommends" mentions. 
> chore: remove all the Medic recommends

- content/en/hosting/4.x/docker/_index.md
- content/en/hosting/4.x/kubernetes/_index.md
- content/en/hosting/_index.md
- content/en/hosting/costs.md
- content/en/hosting/kubernetes-vs-docker.md
- content/en/hosting/requirements.md
Refine the language around Docker vs. Kubernetes to encourage objectivity and leave the choice of the deployment tool up to the reader.
> chore: refine language about docker vs kubernetes

- content/en/building/interoperability/openhim.md
Add additional context to a step in the CHT configuration [section](https://docs.communityhealthtoolkit.org/building/interoperability/openhim/#cht-configuration).
> fix(NA): add additional context to a step in the CHT configuration section

- content/en/technical-overview/architecture/cht-watchdog.md
[per link checker](https://github.com/medic/cht-docs/commit/48667fc198e4a48220727220181e7a63474b0a01/checks)
> fix(na): fix 404 on watchdog

- content/en/building/guides/data/_index.md
- content/en/building/guides/data/audit.md
- content/en/building/reference/app-settings/transitions.md
> chore(): adds audit documentation

- content/en/releases/4_20_0.md
Update 4.20 release notes with all SSO contributors. see related [slack thread](https://medic.slack.com/archives/C024KSXQX/p1749103178435459?thread_ts=1749066307.836199&cid=C024KSXQX)
> fix(na): Update 4.20 release notes with all SSO contributors

- content/en/releases/_index.md
Reduce the size of the unsupported CHT versions table to improve readability. The release dates for older versions can be found in the respective release notes, if needed. 
> chore: reduce the size of supported versions table

- content/en/building/messaging/gateways/rapidpro.md
> fix(#1948): Add notes on global variable naming restrictions

- content/en/community/hall-of-fame.md
Add kudos for security vulnerability disclosure (@syafiq) 
> chore: add kudos for security vulnerability disclosure

- content/en/community/squads.md
Add small language tweaks on the squad page
> chore: add small language tweaks on the squad page

- content/en/hosting/monitoring/integration.md
remove 'version' from docker compose files on [monitoring page](https://docs.communityhealthtoolkit.org/hosting/monitoring/integration/)
> chore(na): remove 'version' from docker compose files

- content/en/building/reference/api.md
Fix references to `/api/v1/records` which should have been `/api/v2/records`
> fix(NA): fix references to /api/v1/records

- .tool-versions
- compose.yml
Upgrade `hugo` to the [latest version](https://github.com/gohugoio/hugo/releases)
> chore: upgrade hugo to 0.149

- content/en/building/messaging/gateways/nepal_doit.md
Configuration guide for integrated Centralized SMS Gateway of Nepal #1964
> feat(#1964): Add a configuration guide for integrated Centralized SMS Gateway of Nepal

- content/en/community/contributing/code/releasing/pyxform.md
Closes https://github.com/medic/pyxform/issues/24
> feat: added pyxform release documentation

- layouts/partials/custom/head-end.html
Per kapa.ai request, update the AI widget text. 
> chore: update kapa.ai text

- layouts/partials/custom/head-end.html
Remove animation from the AI widget, per kapa.ai [documentation](https://docs.kapa.ai/integrations/website-widget/configuration#floating-widget). 
> chore: remove animation from AI widget

- .github/scripts/muffet.sh
Update [muffet.sh](https://github.com/medic/cht-docs/blob/main/.github/scripts/muffet.sh) to ignore all `www.npmjs.com` and YouTube URLs. see [slack](https://medic.slack.com/archives/CUXB9SVT5/p1759184868389009?thread_ts=1759134994.760969&cid=CUXB9SVT5) and GH [CI](https://github.com/medic/cht-docs/commit/a6009d2aef012d79fbb305e1f29881263713f938/checks)
> chore(na):  muffet.sh ignore all www.npmjs.com URLs

- content/en/hosting/medic/deploy-on-eks.md
oops - we need the medic-infro repo cloned ;) 
reverts #1914
> fix(na): oops - we need the medic-infro repo cloned ;)

- content/en/hosting/cht/docker/installation.md
This PR bumps the [docker compose install guide](https://docs.communityhealthtoolkit.org/hosting/cht/docker/installation/) hard coded CHT version from 4.11 to 4.21.1
> chore(na): bump install guide to use 4.21.1

- content/en/building/reference/api.md
> fix(#2023): fix table of content on API Page
