medic/cht-docs

layouts/partials/related.html

Anchors on directories were not being resolved for the relatedContent field. With this change anchors on pages with trailing slashes, like `core/overview/db-schema/#targets`, will work.

Handles anchors on directory pages

---

content/en/apps/reference/forms/contact.md

adds missing `s` on `medic-conf` call
see #171

Fix missing 's' in medic-conf call

---

content/en/core/overview/supported-software.md

Now we support all patches for a minor, instead of just the latest patch,
for 3 months after the subsequent minor is released.

Update software support policy

---

README.md

I think the links to docs.communityhealthtoolkit.org are more canonical than the self-referential links back to this repo.  Very open to input, of course!
#180

Fix doc style guide link being 404

---

content/en/apps/features/integrations/dhis2.md

In the "Overview" section, I fixed a typo from "Franework" to "Framework"

Fixed a typo

---

layouts/_default/search.html

The search now shows the results for the _Documentation_ first. @n-orlowski and I looked at other options of having a primary and secondary search, and in the end we were happy to have a clean way to have highlight the primary search, yet still making the secondary search available. 
For #211

211 - Shows documentation search results first

---

content/en/apps/reference/_partial_functions.md
content/en/apps/reference/_partial_utils.md
content/en/apps/reference/nools-extras.md
content/en/apps/reference/targets.md
content/en/apps/reference/tasks.md
layouts/shortcodes/read-content.html

For #232. Hides the menu item using frontmatter. In doing so we can't use the readfile shortcode/function anymore so added a new shortcode which reads the file content.
Duplication is avoided, but drawback is that the content of the partial file is not in the TOC on the right side -- but this is not a regression. If there is a method to avoid duplication and adds the content to the TOC we should consider it. We could consider making this content a true page, and refer to it via `see-also`. The reason this wasn't chosen so far was that is it nice to have this content inline. Open to other ideas though!

Hide item from menu

---

content/en/_index.md

Currently the main page has two top level titles:
With this change:

Remove double title

---

content/en/apps/concepts/interoperability.md
content/en/apps/features/integrations/_index.md
content/en/apps/features/integrations/rapidpro.md

- updated related content on interoperability page to point to features instead of guides
- added some related content on the integrations index page
- added the top level RapidPro "features" page. This works as a standalone page. I'll create another branch/PR when I build out the "guide" section

RapidPro documentation - Features page

---

.github/workflows/ci.yml
content/en/apps/concepts/users.md

This build adds a call to `hugo build` that exposes bad builds earlier on in the CI process.  We had [an issue where](https://github.com/medic/cht-docs/pull/298#issuecomment-685180595) a broken build was pushed and CI broke at the `All Branches - Run Muffet link checker` stop in a very non obvious way with:
```
dial tcp4 127.0.0.1:1313: connect: connection r#299 ed
##[error]Process completed with exit code 1.
```
This PR fixes that by explicitly running `hugo` early the CI process and it's called "All Branches - Test For Broken Builds in Hugo" so editors will know why their branch isn't passing CI when it breaks.
see #299

fail on bad builds in CI earlier

---

content/en/apps/reference/forms/app.md

Add Xpath specific documentation and highlight the deprecated `+` operator for string concatenation as part of this [issue](https://github.com/medic/cht-core/issues/6490)

Add Xpath specific section

---

.github/workflows/ci.yml
package.json

I'm gonna make a tshirt "@newtewt is my hero" (but let's hope it doesn't [infect all of GH](https://en.wikipedia.org/wiki/Samy_%28computer_worm%29) ;). With newtewt's help, he verified my initial hunch of `autoprefixer` versions upgrading out from under us was indeed the problem.  
Fix was to add a `package.json` and pin the versions. I went ahead pinned both `autoprefixer` and `postcss-cli`.
see  #313
@abbyad  or @nomulex - I don't think we need ya both to do a review.  First come, first served?  I'm easy. 
PR is ready for ya!

Fix CI postcss error

---

content/en/apps/guides/data/csv-to-docs.md

We didn't have these other notation types documented.

Added the rest of the notation types

---

content/en/core/guides/docker-setup.md

there was a subtitle on the [docker page](https://docs.communityhealthtoolkit.org/core/guides/docker-setup/#use-kitematic-gui-for-docker-tools) that had no content.  we should remove it until we have content for it!

remove unused Use Kitematic subtitle

---

content/en/core/overview/db-schema.md

Not rendering properly due to see-also still using `%` instead of `<`
https://docs.communityhealthtoolkit.org/contribute/docs/style-guide/#cross-referencing-content

fix see-also for hydration documentation

---

content/en/design/best-practices/_index.md

Updated typo under https://docs.communityhealthtoolkit.org/design/best-practices/#icons  
It said:
- ANCE Follow-Up
I changed it to
- ANC Follow-Up

Typo in ANC Icons Best Practices

---

content/en/apps/features/integrations/custom.md
content/en/apps/features/integrations/openmrs.md

As per #429
This may be our first use of aliases... @mrjones-plip is this the best way to do redirects when changing the file name? 
Also, should the best practice be to change all references too (one of one done in this PR)?

Rename generic integrations to be custom integrations

---

content/en/apps/tutorials/tasks.md

`parseInt(report.fields.group_assessment) > 3;` returns NaN and the task never appears. What we're actually after is `report.fields.group_assessment.cough_duration`. Fixes #433

fix group_assessment variable access

---

content/en/apps/guides/performance/telemetry.md

Include the app version in which each metadata element was added.

Update telemetry metadata schema

---

content/en/apps/reference/tasks.md

Small corrections:
- Fix schema definition of `actions[n].form`, required only if `actions[n].type` is `'report'`
- Remove wrong `;` in task example
Ticket: https://github.com/medic/medic-conf/issues/358

Fix contact task action schema definition and example code typo

---

content/en/core/faq/_index.md

Ever since launch of the docs site, we've had [this FAQ section](docs.communityhealthtoolkit.org/core/faq/) that is empty.  I think since it's because it's still empty and not being used, we should remove it!

Remove unused FAQ section

---

content/en/apps/reference/tasks.md

Marked `resolvedIf` as optional (conditionally) and added a section on using the default resolve check method
#medic/medic-conf#107
Issue #465

Adding documentation for default task resolve checking method

---

content/en/apps/guides/performance/telemetry.md

Adding documentation about the new properties in telemetry: packageName and versionCode.
CHT-Core: https://github.com/medic/cht-core/pull/7131
CHT-Android: https://github.com/medic/cht-android/pull/182
https://github.com/medic/cht-core/issues/6741

6741 - Adding device info to about page 

---

content/en/apps/reference/api.md

Add `connected_users.count` to the monitoring api documentation

add connected_users.count to the monitoring api documentation

---

content/en/apps/reference/api.md

medic/cht-core#7068
The associated code changes are included on: https://github.com/medic/cht-core/pull/7081

7068 Remove documentation about setting the user's language via the API

---

content/en/apps/guides/hosting/_index.md
content/en/apps/guides/hosting/app-developer.md
content/en/core/guides/docker-setup.md

This PR:
* Adds a new page documenting how to use the new `docker-compose-developer.yml` file
* Makes minor updates/corrections to `core/guides/docker-setup` page
* Adds an intro section on the `apps/guides/hosting` page
per #medic/cht-core/issues/7211

Document how app developers can use docker compose

---

content/en/apps/reference/forms/app.md

**Description**
This PR:
- Adds documentation for display-base64-image widget.
- Adds documentation for android-app-launcher widget.
- Adds documentation for parse-timestamp-to-date xpath function.
Ticket: https://github.com/medic/cht-core/issues/6981
[CHT-Core](https://github.com/medic/cht-core/pull/7248)
[CHT-Android](https://github.com/medic/cht-android/pull/199)
**License**

6981 - documentation for android-app-launcher, display-base64-image and parse-timestamp-to-date

---

content/en/apps/tutorials/tasks.md

Fixes #511  
The reference form was missing `patient_name` calculate field, hence if somebody followed the exmple, they'd run into the problem. This has been fixed.

#511 Add calculation field in form example.

---

content/en/core/guides/update-dependencies.md

The current "Update dependencies" documentation states that version `5.6.0+` of jquery causes issues when used with select2.  This should actually be version `3.6.0+` since there is no `5.6.0` of jquery (currently `3.6.0` is still the latest).

6345 Fix jquery version documented to have select2 bug

---

content/en/core/guides/android/branding.md

Fix a typo in branding.md

---

content/en/apps/reference/app-settings/registrations.md

Corrected `mentrual` to `menstrual`

Fix a typo in `registrations`

---

.github/workflows/ci.yml

best practice is to always have an [upper bounds](https://github.com/marketplace/actions/enforce-timeout-minutes) for a GH action run time.  Looking at [existing actions](https://github.com/medic/cht-docs/actions), our average time is about a 1m5s, so 15 min should be plenty of extra room!

timeout-minutes set to 15

---

content/en/apps/reference/tasks.md

The guide text says:
> You can also use `this.definition.defaultResolvedIf`
But the code snippet shows: `this.defaultResolvedIf`, which does not work

Correcting example code for `defaultResolvedIf`

---

content/en/apps/guides/tasks/_index.md

For #596
Groups the existing task guides that were grouped in a file system folder, but weren't represented in the tree menu.

Add index for Tasks

---

.github/workflows/ci.yml
README.md

https://github.com/medic/cht-core/issues/6574
Updating references from "master" to "main" in a GitHub Action and the readme file.  The repository's default branch has been renamed to "main" already, and it was not breaking, but I considered it was ideal to have these messages and references up to date.

Updating references from "master" to "main"

---

content/en/core/guides/android/branding.md
content/en/core/guides/android/development-setup.md

This PR:
- Removes references of XWalk and Webview since we don't have 2 versions anymore. 
CHT-Android PR: https://github.com/medic/cht-android/pull/236
Ticket:
https://github.com/medic/cht-android/issues/169

169 - Dropping support for Android 4.4

---

layouts/partials/page-meta-links.html
layouts/shortcodes/github-url.html

this fixes the 404 you get right now when you click the "Edit this page" on any of the docs pages right now:
hat trick of: `commit message == branch name == pull request name` all "fix-edit-this-page-404s" \o/
@abbyad - bonus points for the hockey reference?!

fix-edit-this-page-404s

---

content/en/apps/tutorials/contact-and-users-2.md

Currently when creating users with cht-conf using the documentation, the user's doc in the medic db doesn't include the user's full name. This is because `full name` is misrepresented as `name` in the tutorial. As a result the user details in the console will not have a `full name`

Add missing full name in the user doc when creating users

---

content/en/core/guides/android/development-setup.md

This PR adds information about how to generate a coverage report and where to find the report in cht-android
[CHT-Android PR](https://github.com/medic/cht-android/pull/246)

Cht-android coverage report

---

content/en/apps/reference/api.md

This PR documents how to create many new users with the `POST /api/v1/users` and reflects its actual permissions requirements according to [the current state of the code](https://github.com/medic/cht-core/blob/bb825795a52b2e0443b0070fdb8433b215657852/api/src/controllers/users.js#L129)
[Related cht-core PR](https://github.com/medic/cht-core/pull/7454)
medic/cht-core#7490

Update `POST /api/v1/users` documentation for bulk user creation

---

content/en/apps/tutorials/local-setup.md

Step 1 in [this tutorial](https://docs.communityhealthtoolkit.org/apps/tutorials/local-setup/) was inconsistent with the [Docker Image Setup guide](https://docs.communityhealthtoolkit.org/core/guides/docker-setup/). This PR updates that step and consequently step 3 to be consistent with the guide. It also fixes some formatting issues, typos and updates the frequently asked questions.

Make local setup tutorial consistent with the docker guide

---

content/en/apps/tutorials/contact-and-users-1.md

The [Contact and User Management - Part 1](https://docs.communityhealthtoolkit.org/apps/tutorials/contact-and-users-1/) had a reference to 'medic conf' instead of the updated 'cht-conf'.

Update medic conf to cht-conf

---

content/en/apps/guides/forms/form-inputs.md
content/en/apps/guides/tasks/pass-data-to-form.md
content/en/apps/reference/contact-page.md
content/en/apps/reference/forms/app.md
content/en/apps/reference/forms/contact.md

Adds a new page to the Reference Guide that details what input data is available to app/contact forms.
Closes #297

Add documentation on input data available to forms

---

content/en/core/guides/android/development-setup.md

After https://github.com/medic/cht-gateway/pull/183 is merged it won't be much difference in configuring and using the development environment for the CHT-Android apps and CHT-Gateway.

Update development guides with latest changes in the CHT-Gateway app

---

content/en/apps/tutorials/application-graphics.md

Hello, I think for the partners logos config, the file that has to be created or edited is `partners.json` instead of `branding.json`

fix partners conf filename reference

---

content/en/_index.md
content/en/search.md
layouts/_default/baseof.html
layouts/_default/search.html

The [Hugo/Docsy uplift](https://github.com/medic/cht-docs/pull/731) accidentally broke the search page completely.  :cry: 
Basically, the cascading front-matter from the base `_index.md` file caused the `search.md` file to not get treated as a search page. I have made the necessary corrections to the front-matter to fix this. 
However, I also noticed that the search page no longer contained the sidebars. After some investigating I was able to conclude that this was caused by the unintentional deletion of a couple of the default layout files during the refactor.  (Thanks to a a massive oversight on my part I did not realize they were necessary for the proper layout of the Search page.)  I have restored these pages and now the search page should behave as expected!

Fix search page

---

content/en/apps/examples/anc.md

Okay, so this turned out to be a simple, but weird, problem. Ultimately I think this is an order of operations problem and it seems like somewhere along the way Hugo changed which order it was formatting things in and this broke stuff.
I was able to get everything to render properly simply by _un-indenting_ the `workflow-table` shortcode lines in `anc.md`.  For some reason, with everything just not indented, it seemed to get the order of ops correct.  Ultimately, however, this did not seem like the proper fix (since Hugo actually has [an example of nested indented shortcodes](https://gohugo.io/templates/shortcode-templates/#nested-shortcode-image-gallery)), so I kept digging.
Eventually I found Basically, Hugo has two kinds of delimiters:
- `{{% ... %}}` is the [normal delimiter to …

Update ANC Reference App example to fix workflow tables

---

layouts/docs/list.html

Updates the location of the `list.html` page template so that it is actually used.  Hugo will try to use templates from `layouts/docs` before falling back to `layouts/_default`.  So, the [Docsy list template](https://github.com/google/docsy/blob/main/layouts/docs/list.html) was getting resolved first and was not overridden by our custom `list.html`.  
Understandably, this would break the "Related Content" section for any list pages (e.g. [`apps/features/integrations`](https://docs.communityhealthtoolkit.org/apps/features/integrations/)).  However, I do not understand exactly why this broke the related content for pages such as [`apps/features/contacts`](https://docs.communityhealthtoolkit.org/apps/features/contacts/) since that does not fit my understanding of a "list" page....  (This is …

Fix list pages so that Related Content section is displayed

---

content/en/apps/reference/app-settings/user-permissions.md

This PR updates documentation about can_edit permission.
https://github.com/medic/cht-core/issues/6215
[CHT-Core PR](https://github.com/medic/cht-core/pull/7733)

6215 can edit permission

---

.github/workflows/ci.yml
.github/workflows/daily.yml

Updates the GitHub workflows so that they run on the latest `ubuntu-22.04` image.
https://github.com/medic/cht-core/issues/7741

Uplift GitHub workflows to run on ubuntu-22.04

---

content/en/apps/guides/hosting/app-developer.md
content/en/apps/guides/hosting/self-hosting.md
content/en/apps/tutorials/local-setup.md
content/en/core/guides/docker-setup.md

@dianabarsan  - thanks for fielding forum posts about this!  while a temporary fix that we'll have revert fix soon, I think worthy while.
Mirrors works in #801 for docs and already merged  [cht-core PR](https://github.com/medic/cht-core/pull/7828)

convert all compose files to use `docker-compose-developer-3.x-only.yml` until 4.0 is out

---

content/en/contribute/code/workflow.md

We no longer require manual release testing so this section has been updated. Also updated the "triage" section which hasn't been used for some time.

Update documentation removing manual testing

---

README.md
troubleshooting.md

While following the instructions for running `cht-docs` locally on a Mac M1, I needed to perform two extra steps to have `hugo server` work properly:
- Install `Golang`
- Install `postcss-cli`
I tried the setup steps on a second Mac M1, and I needed to install only `Golang` to have `hugo` running.
This PR updates the `troubleshooting.md` document with the extra steps I needed to perform, in case someone else bumps into the same errors.

Document MacOS M1 errors

---

content/en/apps/guides/hosting/core-developer.md

Similar to Ubuntu 18.04, macOS > 12.3 requires additional configuration for having `python2` running correctly. 
This PR documents the required steps.

Document python2 config for MacOS

---

.github/workflows/ci.yml

This change will restore the working build status image in the readme, but I am not certain that this is actually how we want to do it. Will **non-**main builds also be represented by this status? If so we need to reconsider this approach.
An alternative is to remove the status image, which seems to have been broken for several years without complaint.
For https://github.com/medic/cht-docs/issues/870

Revert build name to fix status image

---

content/en/apps/reference/app-settings/transitions.md

Adds documentation for the new `create_users_for_contacts transition.
Issue: https://github.com/medic/cht-core/issues/7703
cht-core changes: https://github.com/medic/cht-core/pull/7709

Add documentation for create_users_for_contacts transition

---

content/en/apps/tutorials/local-setup.md

Until we can figure an easy way to dynamically resolve the latest version, possibly like is [being considered over here](https://github.com/medic/cht-core/pull/7956#issuecomment-1336775724)

Move from master to 4.0.1 as  stop gap

---

content/en/product-handbook/testing/_index.md
content/en/product-handbook/testing/quality-assistance.md

This creates the testing page as well, which is empty aside from the quality assistance link for now. Ideally there would be more here, but I'd rather keep moving than wait for everything else to exist first.

Adding guidance for quality assistance

---

content/en/core/overview/translations.md

There is broken link in [How To Manage Translations documentation](https://docs.communityhealthtoolkit.org/core/overview/translations/#adding-new-languages). In section, Adding new languages link to ddocs/medic/_attachments/translations/messages-XX.properties shows 404 error.
The translations are now under api: https://github.com/medic/cht-core/tree/master/api/resources/translations

Broken link in How To Manage Translations documentation.

---

content/en/apps/guides/updates/preparing-for-4.md

This usage of the `+` operator was previously unknown to me and is out-of-spec.  However, it did work with older versions of Enketo. So, I have added a brief note to the upgrade guide to call out the behavior change.
_(This change was first noted by @binokaryg (and team) when upgrading a project's config to work with CHT `4.x`.)_

Update 4.0 Upgrade Guide to note `+` operator does not work with strings

---

content/en/apps/guides/hosting/4.x/self-hosting-multiple-nodes.md

This PR:
* removes duplicate network declaration of both `cht-net` and `cht-overlay` in compose files.  Keeps it to just one (`cht-net`) and just makes that an overlay network.  This reliably fixes  #medic/cht-core/issues/8050
* instead of having the user manually editing compose files, uses the [concept of compose override files](https://docs.docker.com/compose/extends/). this means users no longer need to manually edit specific parts of files and set up is MUCH less error prone
* ensures that users can just copy and paste commands and it should Just Work :tm:  for a 3 node setup
per #medic/cht-core/issues/8050

Multi-node install docs: Fix couchdb node names, use compose overrides 

---

content/en/apps/guides/debugging/obtaining-logs.md
content/en/apps/guides/hosting/4.x/backups.md
content/en/apps/guides/hosting/4.x/logs.md
content/en/apps/guides/hosting/4.x/self-hosting-multiple-nodes.md
content/en/apps/guides/hosting/4.x/self-hosting-single-node.md

This PR adds two new docs:
* 4.x Backups
* 4.x Logs
As well, it makes some minor tweaks to other related docs to order the TOC on the left, delineate between phone and browser logs and server logs
per #831

Add 4.x logs and backup info, small tweaks elsewhere 

---

content/en/apps/guides/debugging/obtaining-logs.md
content/en/apps/guides/debugging/sharing-4.x-logs.md
content/en/apps/guides/hosting/4.x/logs.md

This PR ads instructions for how to use the recent [compress_and_archive_docker_logs.sh](https://github.com/medic/cht-core/blob/master/scripts/compress_and_archive_docker_logs.sh) script. 
While tempting to put it with the existing [Obtaining Logs](https://docs.communityhealthtoolkit.org/apps/guides/debugging/obtaining-logs/) page, creating a stand alone page with the intent to share logs seemed more appropriate. 
per #medic/cht-core/pull/8061

add cht4 docker logs support script 

---

content/en/apps/guides/hosting/4.x/self-hosting-multiple-nodes.md
content/en/apps/guides/hosting/4.x/self-hosting-single-node.md
content/en/apps/tutorials/local-setup.md

This PR:
* bumps all `curl` requests fetching docker compose files to use `4.1.0` instead of `4.0.1`
* fixes a misnamed `yml` file for the override in the 2nd couchdb node
* renames `couchdb.x` -> `couchdb-x.local` per #medic/cht-core/issues/7962

rename couchdb node name, fix yml name typo, bump cht 4.0.1 -> 4.1.0 in curl

---

content/en/contribute/medic/product-core-competencies/_index.md

The basic heading+description format was fine, but the Hugo template adds an H2 "Feedback" item to the end which at first is a bit confusing as it looks like it's a 6th core competency of "feedback". This format change makes it much more clear what on the page is actually for what.
Here are screenshots showing the formatting confusion and the proposed visual change to avoid it:

Table format for core competencies

---

content/en/contribute/code/core/dev-environment.md

The main differences I have found in the setup steps across the different platforms is in the installation of the various dependencies.  So, I have tried to provide separate steps for each of these.
Using [Docsy's Tabbed Panes](https://www.docsy.dev/docs/adding-content/shortcodes/#tabbed-panes) to specify the actual commands needed for the different environments so that it is clear which commands need to be run on which operating systems.
Note that the change from using `$0` in commands to using `$SHELL` was because on WSL2 (for reasons I cannot explain) `$0` would return `-bash` (with the '-' in front).  This, of course, broke the various commands.  Also, on my Linux, `$0` returns `/usr/bin/zsh`. This also breaks any of the commands trying to write to the `...rc` files.  Since the …

Update Core Dev Setup Guide for non-Linux environments

---

content/en/apps/tutorials/local-setup.md

I realized there was a random param included in the page that we do not want.

Fix typos in app dev guide

---

content/en/apps/guides/hosting/4.x/adding-tls-certificates.md
content/en/apps/guides/hosting/requirements.md

This PR:
* Breaks up the [existing TLS page](https://docs.communityhealthtoolkit.org/apps/guides/hosting/4.x/adding-tls-certificates/) into two parts: one for pre-existing certs and certbot certs via let's encrypt
* updates a bit of the existing [requirements page](https://docs.communityhealthtoolkit.org/apps/guides/hosting/requirements/) to be more up to date.
Per #medic/cht-core/issues/8099

add steps to use certbot with CHT

---

content/en/apps/guides/updates/preparing-for-4.md
content/en/contribute/code/releasing.md
content/en/contribute/code/releasing/_index.md
content/en/contribute/code/releasing/feature_releases.md

Adds clarifications about the release process:
- When a release is made 
- Release process steps
- Responsibilities of the release manager
- Clarifications on `minor`/`major`/`patch` releases
Closes #921

chore(#921): Clarify the release process

---

content/en/apps/reference/tasks.md

As per https://forum.communityhealthtoolkit.org/t/task-title-with-an-array-of-translations/2671/2

fix: remove deprecated configuration option

---

content/en/apps/guides/forms/app-form-sms.md

Found in https://github.com/medic/cht-docs/commit/b5b750899f24d76fdc7ac601734178bb50e7fc48/checks
Given the simplicity of the page, seemed reasonable to deep link to archive.org version of the page (like wikipedia does :thinking: )

Fix 404 to SMS test link page

---

content/en/apps/guides/hosting/monitoring/production.md
content/en/apps/guides/hosting/monitoring/setup.md

This PR:
* Adds a new document talking about how to productioninze grafana by adding a Caddy layer for TLS
* sets left hand table of contents order
per https://github.com/medic/cht-monitoring/issues/29

Add TLS info  for Grafana in monitoring and alerting stack

---

.github/scripts/muffet.sh

The [build](https://github.com/medic/cht-docs/commit/98aa1459e6879b7fc3929bf8d64f6a1c9ed73aec/checks) failed for 3 consecutive days, due to twitter sending `too many redirections` error.

fix: Exclude twitter link from check

---

config.toml

For #1058
Uses the new Analytics ID and format, as per docs: https://www.docsy.dev/docs/adding-content/feedback/

Switches Analytics from UA to GA4

---

content/en/apps/guides/hosting/monitoring/production.md

This PR adds a step in production setup steps of watchdog to set the `root_url` which was recently [added to the example config](https://github.com/medic/cht-watchdog/pull/44).

fix(na) add step to set default grafana URL in .ini

---

content/en/contribute/code/releasing/publish-docker-image.md

This documentation is based on the process followed to publish the new `cht-app-ide` image [from cht-conf](https://github.com/medic/cht-conf/blob/main/.github/workflows/publish_docker_image.yml).

Add documentation for publishing a Docker image

---

config.toml
content/en/apps/guides/hosting/monitoring/integration.md

This PR:
* removes the extra mermaid config
* fixes the numbering on the CHT Watchdog page
The [extra mermaid config](https://github.com/medic/cht-docs/blob/58e3ced0a9230f71adf3f86430fe7b3ae31dc1e4/config.toml#L213) removes the colors and tightens up the charts.  Top is with this PR, bottom is [what is live now](https://docs.communityhealthtoolkit.org/apps/guides/hosting/monitoring/integration/#additional-flows):
[The numbering that is off](https://docs.communityhealthtoolkit.org/apps/guides/hosting/monitoring/integration/#steps-to-new-integrations) that this PR fixes:

fix(na) remove extra mermaid conf fix numbering in watchdog

---

content/en/apps/guides/forms/form-inputs.md

From the conversation in [this forum thread](https://forum.communityhealthtoolkit.org/t/query-parent-contact-place-data-in-child-form/2711/9) it is clear that our current docs around the contact selector functionality is incomplete.  Additionally, the documentation around form inputs for `contact` forms is misleading/wrong.
While not directly related, IMHO this PR closes https://github.com/medic/cht-docs/issues/404.  With this additional documentation, I think we have some fairly comprehensive examples of the different ways you can use the contact selector.

Update docs for contact form inputs and contact selectors

---

content/en/contribute/code/workflow.md

Add clarifications about the Quality Assistance process in the development workflow. Remove all the mentions about Acceptance Testing.
Bonus: Remove "we" mentions.

chore: Clarify Quality Assistance in the dev workflow

---

content/en/apps/concepts/hierarchy.md

This PR adds boxes around the people hierarchy subgraphs to make it more clear what lines are associated with which nodes.  It also lines up the families and family members horizontally. 
Left is what is live, right is what this PR does:

add boxes to people hierarchcy

---

config.toml
content/en/apps/reference/api.md

The empty placeholders were because of using heading sizes that weren't incrementally smaller then the parent (eg: 3 hashes with a subhead of 5 hashes). I manually fixed these, then found there's a config change we can make to simplify the TOC to make it more usable too. As far as I can see this is the only place where we use a TOC so it makes no difference anywhere else.
@mrjones-plip I'm happy to revert the heading size change _or_ the toc change _or_ neither - let me know which you prefer!
#1108

fix(#1108): fix empty placeholders

---

.github/scripts/set_dns.sh
.github/workflows/daily.yml

This PR:
* Adds a new `[set_dns.sh](https://github.com/medic/cht-docs/compare/1106-fix-muffet-dns-issues?expand=1#diff-41bc4f19b66c95e56aa6a4eb3e44559e4f15369d246de7e9c3125a6c681ebfa5)`  script which sets GH CI runner DNS to `9.9.9.9`
* Updates CI to call the new `set_dns.sh` script
* Updates runner names to no longer have "All Branches -" and "Main only" as this script is always called on `main`, never on branches.

fix(#1106) Muffet DNS Issues & CI Names

---

content/en/apps/guides/hosting/monitoring/setup.md

Update cht-watchdog setup guide about absolute path
For #1122

#1122 Update documentation about absolute path

---

content/en/apps/guides/hosting/4.x/adding-tls-certificates.md

This PR updates the 4.x TLS page to:
* have info about the `AUTO_GENERATE` value being set in CHT
* warns that the certbot stuff only works with >4.2
* talks about using `STAGING` certbot servers to do lots of TLS testing without hitting rate limit from certbot: `too many certificates (5) already issued for this exact set of domains in the last 168 hours`
closes #1127

 update TLS docs to include AUTO_GENERATE and other important steps/warnings

---

content/en/apps/reference/api.md

#1145 - Documentation for /api/v1/express-metrics

---

content/en/core/overview/db-schema.md

A report's subject can only be defined via `doc.fields.patient_uuid` never `doc.patient_uuid`.
https://github.com/medic/cht-core/blob/8f328d40b21dd95a6f24606e19c607c75e8dc41d/shared-libs/lineage/src/utils.js#L21 https://github.com/medic/cht-core/blob/69b478371091c0fa3cac00003e04af052050346d/ddocs/medic-db/medic/views/docs_by_replication_key/map.js#L32
It is used here - but that's likely a bug? 
https://github.com/medic/cht-core/blob/899e30df5fc6b7c52c99893609887ae714c87cd0/admin/src/js/services/message-queue.js#L324
I suspect we should not encourage users to set multiple subjects because cht-core appears non-deterministic on which it looks at first.

Report's subject ID cannot be set by `doc.patient_uuid`

---

content/en/apps/reference/app-settings/outbound.md

Adds clarification to `outbound` docs regarding the behavior of the send queue when the outbound configuration is updated with messages still present in the queue.  
[Related Slack discussion](https://medic.slack.com/archives/C024KTGRW/p1691414191385219)

Add doc for changes to outbound config with messages in queue

---

.github/scripts/muffet.sh

back in a8ea000cae45cc0b68b73a082b5beaad1de739a6 the `timeout` was decreased from `35` to `10` let's revert that in hopes of avoiding timeouts per #1161

fix(#1161): increase muffet timout from 10 to 35

---

content/en/contribute/medic/onboarding/technical-resources.md

should fix infinite redirect [per this check](https://github.com/medic/cht-docs/commit/ad3e363f387156878d816a9768963b955dd18161/checks)

fix broken link for dbt install

---

.github/workflows/daily.yml

We get a lot of timeouts in the link checker.
I think because we check so often (every 24 hrs) we catch a lot of websites that are down. This greatly increases our false positives and reduces the trust in this link check script.  With all the noise in the channel, we end up ignoring the reports.
To reduce the noise and to hopefully reduce the false positives, I'm going to reduce the frequency of this script being run to 1/week instead of 1/day.

Run link checker only on Sundays

---

.github/scripts/muffet.sh

Related to [this build fail](https://github.com/medic/cht-docs/commit/281eaa7084677c98ac531386dc225f28bf4039b4/checks).

chore: Exclude Baserow demo from link checker

---

content/en/contribute/code/static-analysis.md

This PR is for adding the documentation, but provides a good place for review/discussion of the planned changes (since they will need to be made manually in the SonarCloud webapp).
Basically, the problem with our current Sonar config is that it is allowing PRs to be merged when they still contain issues!  Any PR that fails our Quality Gate conditions (which currently just is the [`Sonar Way` gate](https://docs.sonarcloud.io/improving/quality-gates/#how-quality-gates-are-defined)) will be blocked from merging (or at least the CI will show as failing). However, if the Quality Gate does not fail, the CI will show as passing _even if Sonar identified issues in the code_.  
You can see this behavior in action on my [test branch](https://github.com/medic/cht-core/pull/8659/checks?check_run_id=17 …

Add custom Sonar Quality Gate

---

content/en/apps/reference/app-settings/schedules.md

Update schedules document to include update on start_from. Required documentation for medic/cht-core#8633

feat (#1207) document changes on start_from property

---

content/en/apps/reference/contact-page.md

Fixed a typo #1240
There was a typo in the Care Guides section:
> The context **_infomation_** from the profile is accessible as the variable summary.

fix(#1240): Fix a typo

---

content/en/apps/reference/forms/contact.md

https://github.com/medic/cht-core/issues/6612
Clarifies that `contact` and `summary` data are not available in contact form expressions.
[Related forum thread](https://forum.communityhealthtoolkit.org/t/disable-members-addition-for-muted-households/3195)
For the record, I believe it is this line that is not passing any value for `user` or `contactSummary`:
https://github.com/medic/cht-core/blob/b7b2629bfe92329f9974e94adc6786bc687f3202/webapp/src/ts/modules/contacts/contacts-content.component.ts#L330

feat(#6612): add note for contact form expression data access

---

content/en/contribute/code/core/dev-environment.md

Update [CHT Core dev environment setup](https://docs.communityhealthtoolkit.org/contribute/code/core/dev-environment/#couchdb-setup-in-cht-4x) to include setup instructions for people using Apple Silicon Macbooks.
In the current Docs, the section [CouchDB Setup in CHT 4.x](https://docs.communityhealthtoolkit.org/contribute/code/core/dev-environment/#couchdb-setup-in-cht-4x:~:text=echo%20%24COUCH_URL-,CouchDB%20Setup%20in%20CHT%204.x,-Create%20a%20docker) includes a command that creates a `docker-compose.yml` file that points to the publicly available images at `public.ecr.aws/medic/cht-couchdb:4.4.0-alpha`
Unfortunately, the images available on there are built for `AMD ` architecture
So when you run the command `COUCHDB_USER=medic COUCHDB_PASSWORD=password docker-compose -f …

chore(#1233): Document CHT installation in new Mac

---

content/en/apps/guides/hosting/4.x/adding-tls-certificates.md

Appears this should be cert.pem.  [This line](https://github.com/medic/cht-docs/blob/main/content/en/apps/guides/hosting/4.x/adding-tls-certificates.md?plain=1#L46) uses cert.pem and it is the default [here](https://github.com/medic/cht-core/blob/34edb11f7f5b9a2f945945387e70a762098c8148/nginx/ssl-install.sh#L5). Docker helper maybe uses chain.pem but I don't think this is the default for cht-core self-host. 

fix(#): consistent naming for public key file

---

content/en/contribute/code/static-analysis.md

chore: remove S2699 sonar rule that requires tests to have assertions

---

content/en/apps/reference/contact-page.md

This adds a further clarification on top of https://github.com/medic/cht-docs/pull/1257 to note that only reports from `person` children are actually passed to the contact-summary.  So, if you have a CHW Area that has some direct `person` children as well as some Households that are also direct children of the CHW Area, the contact-summary for the CHW Area will have access to the reports for the `person` children, but not to reports associated with the Household contacts.

feat(contact-summary): child reports are only from persons

---

content/en/contribute/code/static-analysis.md

Documents the method used in https://github.com/medic/cht-core/pull/8800 to ignore whole code blocks in Sonar.

feat(static-analysis): add doc for ignoring code blocks in Sonar

---

content/en/apps/guides/data/users-bulk-load.md

From [this](https://forum.communityhealthtoolkit.org/t/bulk-user-upload-chws-and-supervisors/2161/19) forum post, it is evident that there is a huge gap between documentation on Bulk user upload and what actually works.The goal of this PR is to make the documentation:
- More detailed(spelt out step by step guide) to ensure users find it easy to upload users in bulk
- Less technical.Since the users of the feature vary from technical to non technical people, the documentation should be less technical
- Less scattered. To ensure one is able to follow the documentation step by step, explanation on what each part of the template spreadsheet does, should be clustered to avoid the user missing out on what the significance of each section is.
- Improve wording to ensure ease in reading

Refining user bulk load documentation

---

content/en/apps/guides/hosting/4.x/data-migration.md

After having multiple instances with preexisting containers have outages due to resource allocation conflicts. 

chore: Remove old containers after 4.x data migration

---

content/en/contribute/code/core/dev-environment.md

This PR reduced the number of manual steps that Apple Silicon users need to take when setting up the CHT Core dev env.  While it sends both Intel  and Apple Silicon user through these steps, it's a safe abstraction (technically all users could take this route).
The `npm run local-images` is a very heavy call, building every image for every service.  We only want the couchDB one.  As well, we don't want different env vars and docker files for macOS folks - this PR keeps all that standard.  
With less steps and less setup needed, I believe this will mean more success for new devs first getting setup!

chore(na) Simplify macos steps to always build couchdb image

---

content/en/contribute/code/core/dev-environment.md

This PR moves the `COUCH_NODE_NAME` and `COUCH_URL` exports into general CHT setup, out of CHT 3.x setup section in CHT Core  developer setup docs

fix(na) move exports into general CHT setup, out of CHT 3.x setup

---

content/en/contribute/code/android/development-setup.md

After https://github.com/medic/cht-android/pull/349, Java 17 will be required to build cht-android.  Also added documentation about how to upgrade the Android System Webview version in an emulated Android device.

feat: update Android dev environment docs to note Java 17

---

content/en/core/releases/_index.md

When adding the [4.6.0 release notes](https://github.com/medic/cht-docs/pull/1309) I forgot to update the dates for the release. :sweat: 

fix: include dates for cht-core 4.6.0 release

---

content/en/contribute/code/core/dev-environment.md

Once we [release](https://github.com/medic/cht-core/issues/8823) `4.6.0`, we'll be on to `4.7.0` and `master` will pick up the new [multi-platform builds](https://github.com/medic/cht-core/issues/8841).   At that time, we should be able to remove the `buildx` macOS specific section of the CHT Core Dev setup docs.

fix(na): Remove macOS specific `buildx` instructios for Core Dev Environment

---

content/en/contribute/medic/product-development-process/transparency-accountability.md

This is primarily for teammates to understand key expectations around our process and why that matters.

Add page on transparency and accountability

---

content/en/apps/reference/forms/app.md

https://github.com/medic/cht-core/issues/8681
Update documentation for the `countdown-timer` widget to specify how to use the new `trigger` functionality.  
cc @SheilaAbby

feat: add doc for new countdown timer form configuration

---

.github/scripts/muffet.sh

ignore good doc muffet check on [team meeting page](https://docs.communityhealthtoolkit.org/contribute/medic/onboarding/team-meetings/)

Update muffet.sh to ignore private google docs page on 

---

.tool-versions
README.md
compose.yml
config.toml

This PR: 
* Adds ability to run `hugo server` with Docker compose in addition to native packages via a newly add `compose.yml` file
* updates readme with steps to use newly added compose file
* bumps `hugo` in `.tool-version`  to `0.122`

feat(na): Bump hugo to 0.122 & add Docker Compose file, update readme

---

assets/scss/_variables_project.scss
go.mod
go.sum

This update from version '0.6.0' to '0.7.0' of the Docsy theme will enable the copy to clipboard feature for blocks of code on the docsite.
This solves https://github.com/medic/cht-docs/issues/977.

Upgrading docsy from 0.6.0 to 0.7.0

---

content/en/contribute/code/core/deploy-on-eks.md

I found this line in the docs abit confusing [Also, do not use quotes "" to enclose your password, and do not use spaces in your password](https://docs.communityhealthtoolkit.org/contribute/code/core/deploy-on-eks/#:~:text=Also%2C%20do%20not%20use%20quotes%20%22%22%20to%20enclose%20your%20password%2C%20and%20do%20not%20use%20spaces%20in%20your%20password). it seems to imply one should not enter the password as a string in the values file.
While you do not explicitly need to wrap `strings` in quotes in `yaml` as explained in [SO post](https://stackoverflow.com/questions/19109912/yaml-do-i-need-quotes-for-strings-in-yaml) and random [blog post](https://brettops.io/blog/yaml-strings/), there are some edge cases. 
Therefore, to avoid any possible issues with setting the bugs lets have the …

Chore: reword to avoid ambiguity

---

content/en/apps/guides/hosting/4.x/self-hosting/_partial_upgrade_service.md
content/en/apps/guides/hosting/4.x/self-hosting/multiple-nodes.md
content/en/apps/guides/hosting/4.x/self-hosting/single-node.md

Adds instructions for how to upgrade the `cht-upgrade-service`.  Below is a draft of a forum post that we could make instructing people to take the upgrade.  Let me know how it sounds!  Thanks!
https://github.com/medic/cht-upgrade-service/issues/38
https://github.com/medic/cht-upgrade-service/pull/37
---
We are happy to announce a new release of the [cht-upgrade-service](https://github.com/medic/cht-upgrade-service)!
CHT `4.x` deployments should follow these steps to install the new version of the CHT Upgrade Service:
- [Single Node - Docker](https://docs.communityhealthtoolkit.org/apps/guides/hosting/4.x/self-hosting/single-node/#upgrading-the-cht-upgrade-service)
- [Multiple Nodes - Docker](https://docs.communityhealthtoolkit.org/apps/guides/hosting/4.x/self-hosting/multiple-node/#upgrad …

feat: add docs for upgrading the cht-upgrade-service

---

content/en/apps/guides/hosting/4.x/self-hosting/_partial_upgrade_service.md

Noticed typo right after publishing these new docs...

fix: correct typo in docs for upgrading the cht-upgrade-service

---

content/en/hosting/monitoring/setup.md

Describes how to use YAML files to allow watchdog to monitor a remote postgres instances for couch2pg backlog but not need any postgress credentials or have an SSH tunnel to the server
If following these steps, please be sure to use `stand-alone-couch2pg-backlog-99` branch when testing as the changes are not yet in `main`.  This needs to be done on test Postgres server as well as test Watchdog server.
per https://github.com/medic/cht-watchdog/issues/99

feat(na): add setup steps for stand along SQL Expoerter on Posgtres server

---

content/en/apps/guides/database/database-conflicts.md

Removed any medic-specific information like which channel the notification for conflicts shows up. Also, I searched the channel and the latest conflict notification was on May 2, 2020.

chore: Remove medic specific information from database conflict resolving documentation

---

content/en/hosting/4.x/self-hosting/_partial_upgrade_service.md

It looks like the partial for upgrading the upgrade service got duplicated (maybe by some git-foo). The result on the [docs site](https://docs.communityhealthtoolkit.org/hosting/4.x/self-hosting/single-node/#follow-the-product-releases-channelhttpsforumcommunityhealthtoolkitorgcproductreleases26-on-the-cht-forum-to-stay-informed-about-new-releases-and-upgrades) looks very confusion!  :sweat_smile: 

fix: remove duplicate docs for upgrading the cht-upgrade-service

---

content/en/apps/guides/android/branding.md

Fix the link in the [Building CHT Android Flavors page](https://docs.communityhealthtoolkit.org/apps/guides/android/branding/#5-release-the-new-flavor) in the [Release section](https://docs.communityhealthtoolkit.org/apps/guides/android/branding/#5-release-the-new-flavor) that was redirecting to the publishing page instead. New link to release page is [this](https://docs.communityhealthtoolkit.org/contribute/code/android/releasing/) instead.
Fixes: #1399

fix: Fix link in Create your Android Flavor's Release section

---

content/en/apps/guides/privacy/privacy-policy.md

Clarified location of privacy-policies.json file in the documentation
The guide has been updated to specify that the privacy-policies.json file should reside in the root of the project directory rather than inside the privacy_policies folder. This change ensures users place the file correctly to avoid configuration issues during the upload-privacy-policies action.

fix(#1403): Improve 'Adding Privacy Policies to Apps'

---

content/en/contribute/code/_index.md
content/en/contribute/code/hall-of-fame.md

The security researcher hall of fame is something we've quoted in our docs but never had one because nobody has ever disclosed a vulnerability outside of Medic before. Until now!
This is what it looks like (on my machine).

feat: add contributor hall of fame

---

content/en/apps/reference/app-settings/transitions.md

Just trying to clarify the muting transition docs re: [this forum conversation](https://forum.communityhealthtoolkit.org/t/is-it-possible-for-a-contact-edit-form-to-trigger-the-mute-action/3543/1
)

Clarify muting transition configuration options

---

content/en/apps/guides/data/analytics/building-dbt-models.md

Add a description about the couchdb lambda view.
https://github.com/medic/cht-docs/issues/1328

docs: add a description about the couchdb lambda view

---

content/en/core/releases/4.0.0.md
content/en/core/releases/4.0.1.md
content/en/core/releases/4.1.0.md
content/en/core/releases/4.1.1.md
content/en/core/releases/4.1.2.md
content/en/core/releases/4.2.0.md
content/en/core/releases/4.2.1.md
content/en/core/releases/4.2.2.md
content/en/core/releases/4.2.3.md
content/en/core/releases/4.3.0.md
content/en/core/releases/4.3.1.md
content/en/core/releases/4.4.0.md
content/en/core/releases/4.4.1.md
content/en/core/releases/4.4.2.md
content/en/core/releases/4.5.0.md
content/en/core/releases/4.5.1.md
content/en/core/releases/4.5.2.md
content/en/core/releases/4.6.0.md
content/en/core/releases/4.7.0.md
content/en/core/releases/4.7.1.md
content/en/core/releases/4.8.0.md

This PR uses a [hacked version](https://github.com/medic/cht-core/blob/mrjones-hack-get-contributors-only/scripts/release-notes/index.js) of the new release note script to back-fill contributors on all 4.x versions except `4.2.4` and `4.3.2` which have some weird error that I don't want to chase down.
We shouldn't merge the  [ephemeral branch](https://github.com/medic/cht-core/blob/mrjones-hack-get-contributors-only/scripts/release-notes/index.js) `mrjones-hack-get-contributors-only`  on CHT Core repo, but published it for posterity.
the output of the bash wrapper [script used](https://github.com/medic/cht-core/blob/mrjones-hack-get-contributors-only/scripts/release-notes/get.contributors.sh) script `get.contributors.sh`:
```
./get.contributors.sh
saving version 4.0.0 to …
```

 chore(na): add prior contributors fof 4.x releases

---

layouts/partials/sidebar-tree.html

Migrates data-toggle to data-bs-toggle and data-target to data-bs-target to fix the hamburger menu on smaller screens.
Fixes #1374.

fix(#1374): migrate navbar toggle menu to bootstrap 5

---

content/en/contribute/code/core/automated-tests.md

Add an extra environment variable (`BASE_VERSION`) to be able to execute successfully the upgrade tests locally

core: add the env variable run the upgrade tests locally

---

content/en/apps/reference/api.md

https://github.com/medic/cht-core/issues/9194
Code changes: https://github.com/medic/cht-core/pull/9177
Related Docs PR: https://github.com/medic/cht-docs/pull/1422

feat(#9194): add api doc for getting place by UUID

---

content/en/contribute/code/android/releasing.md

1. Change the Production Release action item sequence i.e. put the create CHANGELOG action item before creating the tag.
2. A few grammatical fixes

chore: Change Production Release action item sequence for cht-android

---

content/en/apps/guides/android/branding.md

For apps distributed through the Play Store using Google Play Console signing, domain verification fails even after adding the SHA256 fingerprint used to build the app.
This PR updates the CHT Android Flavors documentation to include detailed instructions for apps signed by Google Play. Specifically, it addresses the need to use the SHA256 fingerprint provided by the Google Play Console for successful domain verification.
These updates are crucial for ensuring that apps signed by Google Play are correctly associated with their respective domains, allowing for seamless deep linking and improved user experience.

Update Android documentation for Google Play signed app domain verification

---

config.toml
content/en/contribute/code/cht-conf.md

Fix deprecated values of persistLang and language.en:
> ERROR deprecated: config: languages.en.description: custom params on the language top level was deprecated in Hugo v0.112.0 and will be removed in Hugo 0.127.0. Put the value below [languages.en.params]. See https://gohugo.io/content-management/multilingual/#changes-in-hugo-01120
ERROR deprecated: config: languages.en.time_format_default: custom params on the language top level was deprecated in Hugo v0.112.0 and will be removed in Hugo 0.127.0. Put the value below [languages.en.params]. See https://gohugo.io/content-management/multilingual/#changes-in-hugo-01120
ERROR deprecated: config: languages.en.time_format_blog: custom params on the language top level was deprecated in Hugo v0.112.0 and will be removed in Hugo 0.127.0. Put the …

Fix deprecated values

---

content/en/contribute/code/core/deploy-on-eks.md

* mention `set-context`  on first use
* update `update-kubeconfig` to be what `eks-aws-mfa-login` returns:
```
$ eks-aws-mfa-login mrjones 040966
Assumed EKS role for mrjones. kubectl -n mrjones-dev get pods should now work. Or you have been notified about other namespaces you have access to.
If this is your first time logging in, please run 'aws eks update-kubeconfig' from README.md instructions found in this repo
E.g. aws eks update-kubeconfig --name dev-cht-eks --profile mrjones --region eu-west-2
```

mention set-context on first use, update update-kubeconfig call

---

content/en/apps/guides/updates/preparing-for-4.md

We still have partners upgrading from `3.x` to `4.x`, so the Upgrade Prep guide remains relevant documentation.  However, there are some changes to the "Known issues" with Enekto in the more recent versions of `4.x` (which are likely the versions that partners will be upgrading to).  
This PR updates the docs around the known Enketo issues with the goal of providing useful and relevant information to partners currently trying to prepare for an upgrade.  

feat: update known Enketo issues for 4.x upgrade

---

content/en/apps/reference/api.md

https://github.com/medic/cht-core/issues/9389
[Code PR](https://github.com/medic/cht-core/pull/9390)
Also moved the docs from the `People` section (which is documenting `api/v1/people`) up to the `Person` section (for the `api/v1/person` endpoint).

fix(#9389): update api/v1/person query param to type

---

.tool-versions
compose.yml

The `jakejarvis/hugo-extended` is unmaintained (as is the `klakegg/hugo` which I have also used).  Instead, there is a different [community maintained image](https://discourse.gohugo.io/t/the-up-to-date-hugo-docker-images/43293).  
I am honestly a bit mystified by the terrible SEO for `hugomods/hugo`.  Just from the pull counts it is orders of magnitude more popular than other images, but does not surface at the top in the results list on Docker Hub or in a DuckDuckGo search....
It looks like the [base versions of the image](https://docker.hugomods.com/docs/tags/#latest) contain what we need!  (Extended + Go + Node...). Might be able to get away with one of the more specific ones, but not sure how useful it is to get super picky about the size of a docker image for development usage... …

feat: update docker image to have proper Hugo version

---

compose.yml

fixes this error on `docker compose up`:
```
WARN[0000] /home/mrjones/Documents/MedicMobile/cht-docs/compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
```

remove deprecated services line from compose file

---

content/en/apps/guides/data/analytics/environment-variables.md

Add the required permission when using a fin-grained Github Personal Access Token for cht-pipeline

docs: add the required permission when using a fine-grained access token for cht-pipeline

---

content/en/hosting/4.x/app-developer.md

* update the manual app dev to be more like [prod docker](http://localhost:1313/hosting/4.x/self-hosting/single-node/) docs
* `docker-compose` -> `docker compose`
* always use `.env` files
* remove now redundant `.env` section
* move docker helper to be the top most section
* clearly call out that manual `docker compose` and Docker Helper achieve the same end result (as opposed to needing to run both)

App Dev Hosting: work work manual steps, move docker helper to the top

---

content/en/building/guides/debugging/secure-sharing-of-developer-instance.md
content/en/hosting/3.x/app-developer.md
content/en/hosting/4.x/app-developer.md

Fixed bad links ran on 22nd September 2024.
```
Run ./.github/scripts/muffet.sh
http://localhost:1313/hosting/3.x/app-developer/
404	http://localhost:1313/building/tutorials/local-setup/privacy.error.png
http://localhost:1313/contribute/medic/onboarding/technical-resources/
403	https://www.udacity.com/course/asynchronous-javascript-requests--ud109
tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2024-09-22T03:26:42Z is after 2024-09-20T09:03:01Z	https://pouchdb.com/guides/
http://localhost:1313/hosting/4.x/app-developer/
404	http://localhost:1313/building/tutorials/local-setup/privacy.error.png
http://localhost:1313/building/guides/debugging/secure-sharing-of-developer-instance/
404 …
```

Fix 23 bad links

---

.github/workflows/cron-check-links.yml

Fix which GH user link validation slack alerts come from per medic/cht-docs/issues/1552 . I think the last person to edit the CI is the GH user that slack shows.  Let's find out!

fix(#1552): GH user link validation slack alerts come from

---

content/en/building/guides/training/training-cards-resources/_index.md

- Moving the link to the training card feature page to the top to avoid navigating away in the example section
- Adding clarification that one needs to edit the example training card files with `role` and `start_date` in order to see them.
Closes #1576 

chore(#1576): add clarity to training card guide

---

content/en/building/guides/data/analytics/production.md
content/en/building/guides/integrations/fhir.md

Fix typos in the documentation about CHT Sync and CHT Interoperability. 
Additionally, per the [Style guide](https://docs.communityhealthtoolkit.org/contribute/docs/style-guide/), avoid mentions of "we".
This PR also removes repetitive linking to FHIR resources throughout the same documentation.  

chore: Fix typos in CHT Sync and CHT Interoperability documentation

---

content/en/contribute/code/core/deploy-on-eks.md

Changes instructions and copy/paste code snippet to use the current shell for the autocomplete setup. This allows someone to run the code as documented without needing to change the shell value from zsh to whatever they are using (even though zsh is the correct answer ;) ).

Dynamic shell for autocomplete on k8s docs

---

content/en/building/reference/api.md
content/en/core/releases/4.11.0.md

* fix link for api docs in 4.11 release
* we're zero based for person API pagination, start at 0 instead of 1

fix(na): fix link for api docs in 4.11 release, correct cursor number in API docs

---

content/en/contribute/code/core/deploy-on-eks.md

* removes trailing backtick
* adds step to replace account-id
* re-order values changes to follow file order

fix(na): fix up eks install steps per feedback

---

content/en/building/guides/updates/preparing-for-4.md

avoids returning results in SQL for `null` versions in telemetry which we already do in the [2nd query](https://docs.communityhealthtoolkit.org/building/guides/updates/preparing-for-4/#users-in-need-of-upgrade)

add where clause to exclude null versions on telemetry

---

content/en/contribute/medic/product-development-process/deploy-on-eks.md

Once we merge https://github.com/medic/helm-charts/pull/32 we should merge this PR!
note that [old values](https://github.com/medic/medic-infrastructure/pull/1078) file is being deleted.

Update EKS values file  used in setup

---

content/en/building/contact-summary/contact-summary-templated.md

Currently the [contact-summary `fields` docs](https://docs.communityhealthtoolkit.org/building/contact-summary/contact-summary-templated/#contact-summarytemplatedjs-fields) indicate that the `appliesIf` property for a field could be:
> `function()` or `boolean`
However, checking the [actual code in cht-conf](https://github.com/medic/cht-conf/blame/da017f990c954950afb1235e90ca7ea6b2179d9a/src/contact-summary/contact-summary-emitter.js#L17), there is no way that a `boolean` value could be set here with a semantically logical meaning.  
```js
if (!f.appliesIf || f.appliesIf()) {
```
If you set `appliesIf = false`, this if-statement would resolve `true` because `!false === true`.  If you set `appliesIf = true`, then we get the error `TypeError: f.appliesIf is not a function` because it will …

fix: correct docs for contact-summary field `appliesIf`

---

content/en/building/reference/app-settings/transitions.md

This PR seeks to close issue https://github.com/medic/cht-docs/issues/509.
The [transitions documentation](https://docs.communityhealthtoolkit.org/building/reference/app-settings/transitions/)
contained footnotes that not only made it confusing to read, but were not standard with the rest of the documentation format. To achieve uniformity and improve readability. This PR includes changes that have:
- Removed superscripts that were used as a reference to the footnote information provided within the page
- Converted the footnote reference to a collapsible paragraph as the information is detailed and optional to the readers)(serves as additional information)
- Fixed some grammatical errors
- Changed some heading/subheading levels to make right-hand navigation easier and neater.
Future …

Remove footnotes

---

content/en/contribute/code/core/automated-tests.md

This update is to address the changes implemented in the ticket [cht-core/#9630](https://github.com/medic/cht-core/issues/9630) where now, using the command `npm run ci-webdriver-default` we can run the e2e tests without re-building the docker images.

chore: add section to debug e2e tests

---

content/en/contribute/code/static-analysis.md
content/en/contribute/code/workflow.md

Since the Dev Workflow docs are a logical starting place for code contributors, this PR adds a bit of linkage to our existing static analysis docs to inform developers about the tools in place to support code quality.  The goal is to reduce/eliminate developers being surprised when the CI for their PR fails due to linting issues.

feat: add linkage from dev workflow to static analysis

---

.github/workflows/cron-check-links.yml

This PR fixes the path for muffet in CI.  Prior path was `muffet.sh` and needed to be `./muffet.sh`.  I went with a more explicit path `./.github/scripts/muffet.sh` which is what we were using before
hopefully will fix #1737

fix(#1737): change path muffet chmod and execute calls

---

content/en/building/concepts/access.md

We'd [just released](https://github.com/medic/cht-docs/pull/1711) the docs for the password change on first login feature which had it as being released in 4.16, but is currently [set for 4.17](https://github.com/medic/cht-core/milestone/140)

fix(na): password change feature to be on 4.17 vs 4.16

---

content/en/core/overview/transitions.md

Fix some typos and grammatical errors on the sentinel transitions page.

chore: fix some typos in transitions.md

---

content/en/building/_index.md
content/en/building/training/training.md
content/en/core/_index.md
content/en/design/_index.md

- Move the `CHT Core Framework` section before the `Designing` section.
- Move solitary `Training` page under the `Training` section.
Before:
After:

chore: order sections and move training page to Training section

---

content/en/contribute/code/workflow.md

chore(#1763): update dev workflow to mention forks

---

content/en/contribute/docs/style-guide.md

Fix `404` URL per link checker.
```
4m 18s
Run chmod +x ./.github/scripts/*muffet*
http://localhost:[1](https://github.com/medic/cht-docs/commit/39ab3ef13feb1598abffb3e58c32447e09cdc49d/checks#step:7:1)313/contribute/docs/style-guide/
404	https://gohugo.io/content-management/cross-references/
Error: Process completed with exit code 1.
```
Please note that ref and relref became redundant and this documentation might need a more thorough review:
>When working with the Markdown [content format](https://gohugo.io/content-management/formats/), this shortcode has become largely redundant. Its functionality is now primarily handled by [link render hooks](https://gohugo.io/render-hooks/images/#default), specifically the embedded one provided by Hugo. This hook effectively addresses all the use …

fix: fix hugo url

---

content/en/hosting/analytics/building-dbt-models.md
content/en/hosting/analytics/environment-variables.md
content/en/hosting/analytics/setup-docker-compose.md
content/en/hosting/analytics/setup-kubernetes.md
content/en/hosting/analytics/tuning-dbt.md

Docs for upcoming CHT Sync v2 release.  This PR:
* adds setup info for V2
* adds setup info for local DBT models (instead of remote files checked into `git`)
* covers new compose deployments using profiles
When following setup steps in this docs PR, be sure your CHT Sync repo is on the `v2` [branch](https://github.com/medic/cht-sync/tree/v2) per [this PR](https://github.com/medic/cht-sync/pull/202). That will make sure the ` --profile` logic is added to the compose files and the `.env` created from the example on has the new `DBT_LOCAL_PATH` value.

feat(#1782): documentation for cht-sync v2

---

content/en/building/reference/app-settings/_index.md

Closes #1770 
(since the last PR  i raised had some other changes which were already merged in this pr i have made sure that only the changes done related to this issue would be shown ) 
Changes Made:
>Clarified the difference between ancestor:<type> and link:<type>
>Updated wording for accuracy and simplicity
>Improved formatting of the table for readability

Improve Documentation for ancestor: and link: SMS Recipient Logic

---

content/en/building/guides/performance/purging.md

This PR updates the `purging.md` documentation to clarify that removing the `purge` key from `app_settings.json` does **not** disable purging. Instead, the purge key must be set to an empty object (`{}`).
Closes https://github.com/medic/cht-docs/issues/1816  

feat(#1816): clarify how to disable purging in app_settings

---

content/en/building/reference/api.md

This PR closes #1538 by improving the clarity of the `/api/v1/users/{{username}}` endpoint documentation.
- ✅ Added an internal link to the "Supported Properties" section to make "Properties listed above" more understandable.
- ✅ Removed the misleading reference to the "People section" since it currently has no content, avoiding user confusion.
This improves the overall readability and usability of the API docs.

fix(#1538): clarify supported properties reference

---

content/en/hosting/4.x/docker/_index.md
content/en/hosting/4.x/docker/adding-tls-certificates.md
content/en/hosting/4.x/docker/backups.md
content/en/hosting/4.x/docker/installation.md
content/en/hosting/4.x/docker/logs.md
content/en/hosting/4.x/kubernetes/gcp-multinode.md
content/en/hosting/4.x/kubernetes/self-hosting-k3s-multinode.md

After moving hosting directory structure in [a recent PR](https://github.com/medic/cht-docs/pull/1873), I see now redirects were missing or broken.  This PR fixes all those redirects
eg `/hosting/4.x/production/docker/` -> `/hosting/4.x/docker/installation/` which didn't work before

fix redirects after hosting content reshuffle

---

.github/scripts/muffet.sh

Exclude `405` and `403` URLs per link checker script:
```
Run chmod +x ./.github/scripts/*muffet*
http://localhost:1313/building/integrations/dhis2-aggregate/
405	https://docs.dhis2.org/2.34/en/dhis2_implementation_guide/data-elements-and-custom-dimensions.html#data-elements
405	https://docs.dhis2.org/2.34/en/dhis2_implementation_guide/data-sets-and-forms.html#what-is-a-data-set
405	https://docs.dhis2.org/2.34/en/dhis2_implementation_guide/integration-concepts.html#integration-concepts
405	https://docs.dhis2.org/2.34/en/dhis2_implementation_guide/organisation-units.html
405	https://docs.dhis2.org/master/en/developer/html/apps_creating_apps.html
405	https://docs.dhis2.org/master/en/developer/html/webapi_data_values.html
http://localhost:[13](https://github.com/medic/cht-docs/commit/3fd99897 …
```

chore: exclude failing urls

---

content/en/community/contributing/creating-good-first-issues.md

Tickets created from the new template on good first issue page don't like the line breaks.  removing them!

chore(na): removing line breaks so tickets look good

---

hugo.toml

Change `flexsearch` `tokenize` parameter to `full` to increase the number of results returned by the search.
Per [documentation](https://github.com/nextapps-de/flexsearch#tokenizer-partial-match) + [additional documentation](https://lotusdocs.dev/docs/features/flexsearch/): 
- `strict` - Only exact matches for the search term will be shown in the results.
- `forward` (default) - Words are searched for starting from the first letter in a forward order, allowing partial matches to be displayed; unfinished words or words with mispellings at the end will still display results e.g. if searching for ‘Testing’, entering only ‘Tes’ will provide some results.
- `reverse` - A result will be shown when the letters of the search term occur in both forward or reverse order, provide even more support …

chore(#2006): change flexsearch tokenize to full
